/*
	For this script to work, the script DBSetup.sql must be run first,
	so that any auto incremented id numbers are regenerated.
	But this will delete any content previously registered in the database
*/

INSERT INTO bikes (price, purchaseDate, make, type) VALUES (3353, "2018-04-14", "DBS", "Bysykkel");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (1676, "2018-04-14", "Trek", "Hybrid");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (1544, "2018-04-14", "Scott", "Hybrid");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (982, "2018-04-14", "Scott", "Terreng");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (2234, "2018-04-14", "Merida", "Bysykkel");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (4059, "2018-04-14", "Merida", "Hybrid");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (572, "2018-04-14", "Scott", "Terreng");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (4314, "2018-04-14", "Scott", "Landevei");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (3492, "2018-04-14", "DBS", "Bysykkel");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (1278, "2018-04-14", "DBS", "Bysykkel");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (4120, "2018-04-14", "Scott", "Terreng");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (3703, "2018-04-14", "DBS", "Hybrid");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (4511, "2018-04-14", "Merida", "Terreng");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (2067, "2018-04-14", "Scott", "Terreng");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (3078, "2018-04-14", "Scott", "Terreng");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (3891, "2018-04-14", "DBS", "Landevei");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (2015, "2018-04-14", "Trek", "Hybrid");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (4815, "2018-04-14", "Merida", "Bysykkel");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (624, "2018-04-14", "Scott", "Hybrid");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (4487, "2018-04-14", "Trek", "Terreng");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (4973, "2018-04-14", "Merida", "Hybrid");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (586, "2018-04-14", "Trek", "Bysykkel");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (4873, "2018-04-14", "DBS", "Landevei");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (3632, "2018-04-14", "Scott", "Terreng");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (2538, "2018-04-14", "Trek", "Bysykkel");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (2769, "2018-04-14", "Scott", "Landevei");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (4306, "2018-04-14", "Trek", "Landevei");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (2868, "2018-04-14", "Merida", "Terreng");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (1285, "2018-04-14", "Trek", "Bysykkel");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (3711, "2018-04-14", "Scott", "Terreng");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (3587, "2018-04-14", "Trek", "Landevei");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (3042, "2018-04-14", "Merida", "Landevei");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (4268, "2018-04-14", "DBS", "Landevei");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (4339, "2018-04-14", "Merida", "Landevei");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (3995, "2018-04-14", "Trek", "Hybrid");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (3395, "2018-04-14", "Trek", "Terreng");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (4216, "2018-04-14", "Trek", "Hybrid");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (3608, "2018-04-14", "Trek", "Landevei");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (2700, "2018-04-14", "Merida", "Bysykkel");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (2420, "2018-04-14", "DBS", "Bysykkel");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (914, "2018-04-14", "DBS", "Terreng");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (1531, "2018-04-14", "Scott", "Landevei");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (4735, "2018-04-14", "Scott", "Bysykkel");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (921, "2018-04-14", "Trek", "Bysykkel");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (1107, "2018-04-14", "Merida", "Landevei");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (3977, "2018-04-14", "Merida", "Bysykkel");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (2691, "2018-04-14", "Scott", "Landevei");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (3700, "2018-04-14", "Merida", "Terreng");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (2947, "2018-04-14", "Scott", "Hybrid");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (1813, "2018-04-14", "Merida", "Landevei");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (4638, "2018-04-14", "Merida", "Hybrid");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (1096, "2018-04-14", "DBS", "Landevei");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (1967, "2018-04-14", "Merida", "Hybrid");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (4189, "2018-04-14", "DBS", "Bysykkel");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (2904, "2018-04-14", "DBS", "Terreng");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (3629, "2018-04-14", "DBS", "Landevei");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (2152, "2018-04-14", "Trek", "Bysykkel");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (1986, "2018-04-14", "Scott", "Landevei");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (2129, "2018-04-14", "Merida", "Hybrid");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (1384, "2018-04-14", "Merida", "Bysykkel");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (3940, "2018-04-14", "Trek", "Landevei");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (4098, "2018-04-14", "Scott", "Landevei");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (2458, "2018-04-14", "Scott", "Hybrid");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (2755, "2018-04-14", "Trek", "Hybrid");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (2300, "2018-04-14", "Scott", "Hybrid");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (1346, "2018-04-14", "DBS", "Landevei");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (1672, "2018-04-14", "DBS", "Bysykkel");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (4527, "2018-04-14", "Scott", "Hybrid");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (3676, "2018-04-14", "DBS", "Bysykkel");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (576, "2018-04-14", "DBS", "Bysykkel");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (4917, "2018-04-14", "Trek", "Terreng");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (2103, "2018-04-14", "DBS", "Bysykkel");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (4640, "2018-04-14", "Trek", "Hybrid");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (2318, "2018-04-14", "Scott", "Hybrid");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (664, "2018-04-14", "Trek", "Terreng");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (4785, "2018-04-14", "Trek", "Hybrid");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (3035, "2018-04-14", "DBS", "Terreng");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (3623, "2018-04-14", "Scott", "Hybrid");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (3531, "2018-04-14", "Trek", "Hybrid");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (2980, "2018-04-14", "Scott", "Bysykkel");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (2702, "2018-04-14", "Trek", "Hybrid");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (1239, "2018-04-14", "Trek", "Hybrid");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (1836, "2018-04-14", "DBS", "Bysykkel");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (1101, "2018-04-14", "Merida", "Bysykkel");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (1239, "2018-04-14", "DBS", "Terreng");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (3270, "2018-04-14", "Scott", "Hybrid");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (2218, "2018-04-14", "Scott", "Bysykkel");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (2212, "2018-04-14", "Scott", "Landevei");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (1160, "2018-04-14", "Scott", "Terreng");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (2654, "2018-04-14", "Scott", "Bysykkel");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (2439, "2018-04-14", "DBS", "Terreng");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (2166, "2018-04-14", "DBS", "Terreng");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (4085, "2018-04-14", "DBS", "Landevei");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (4894, "2018-04-14", "Trek", "Landevei");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (1167, "2018-04-14", "Merida", "Bysykkel");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (2793, "2018-04-14", "Merida", "Bysykkel");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (3521, "2018-04-14", "Trek", "Terreng");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (4771, "2018-04-14", "Trek", "Hybrid");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (971, "2018-04-14", "Trek", "Hybrid");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (1164, "2018-04-14", "Scott", "Landevei");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (4460, "2018-04-14", "Merida", "Terreng");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (4637, "2018-04-14", "Merida", "Landevei");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (2831, "2018-04-14", "Merida", "Hybrid");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (1181, "2018-04-14", "DBS", "Hybrid");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (2386, "2018-04-14", "Trek", "Bysykkel");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (4087, "2018-04-14", "Merida", "Hybrid");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (1278, "2018-04-14", "Merida", "Hybrid");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (3658, "2018-04-14", "DBS", "Hybrid");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (891, "2018-04-14", "Scott", "Hybrid");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (4152, "2018-04-14", "Merida", "Terreng");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (905, "2018-04-14", "Merida", "Hybrid");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (2119, "2018-04-14", "Merida", "Terreng");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (2549, "2018-04-14", "Merida", "Landevei");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (1138, "2018-04-14", "Scott", "Terreng");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (3711, "2018-04-14", "DBS", "Bysykkel");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (2974, "2018-04-14", "DBS", "Bysykkel");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (4262, "2018-04-14", "Merida", "Bysykkel");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (4574, "2018-04-14", "Merida", "Bysykkel");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (2932, "2018-04-14", "Merida", "Landevei");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (504, "2018-04-14", "Scott", "Landevei");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (3803, "2018-04-14", "DBS", "Terreng");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (1594, "2018-04-14", "Trek", "Bysykkel");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (1100, "2018-04-14", "Trek", "Landevei");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (4861, "2018-04-14", "Merida", "Landevei");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (671, "2018-04-14", "Merida", "Bysykkel");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (3502, "2018-04-14", "Scott", "Bysykkel");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (3088, "2018-04-14", "Trek", "Hybrid");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (2984, "2018-04-14", "DBS", "Terreng");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (4816, "2018-04-14", "Scott", "Landevei");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (2882, "2018-04-14", "Merida", "Hybrid");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (1924, "2018-04-14", "Scott", "Landevei");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (4360, "2018-04-14", "Trek", "Terreng");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (4589, "2018-04-14", "Scott", "Hybrid");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (1642, "2018-04-14", "Merida", "Bysykkel");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (1600, "2018-04-14", "DBS", "Bysykkel");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (4575, "2018-04-14", "Trek", "Hybrid");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (3837, "2018-04-14", "Trek", "Landevei");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (3284, "2018-04-14", "Scott", "Landevei");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (997, "2018-04-14", "Merida", "Landevei");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (3332, "2018-04-14", "Merida", "Terreng");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (4651, "2018-04-14", "Scott", "Terreng");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (1983, "2018-04-14", "Scott", "Bysykkel");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (4415, "2018-04-14", "Merida", "Landevei");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (4045, "2018-04-14", "DBS", "Hybrid");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (4407, "2018-04-14", "DBS", "Bysykkel");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (533, "2018-04-14", "Trek", "Hybrid");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (3430, "2018-04-14", "Merida", "Terreng");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (1715, "2018-04-14", "Merida", "Hybrid");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (2853, "2018-04-14", "Scott", "Bysykkel");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (2811, "2018-04-14", "Scott", "Terreng");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (2878, "2018-04-14", "DBS", "Terreng");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (2738, "2018-04-14", "Scott", "Bysykkel");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (2965, "2018-04-14", "Trek", "Landevei");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (3841, "2018-04-14", "DBS", "Landevei");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (560, "2018-04-14", "Merida", "Landevei");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (4694, "2018-04-14", "Merida", "Landevei");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (551, "2018-04-14", "Merida", "Hybrid");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (4712, "2018-04-14", "Scott", "Bysykkel");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (1471, "2018-04-14", "DBS", "Hybrid");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (512, "2018-04-14", "Scott", "Terreng");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (501, "2018-04-14", "Scott", "Bysykkel");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (4448, "2018-04-14", "Merida", "Landevei");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (2975, "2018-04-14", "Scott", "Bysykkel");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (1974, "2018-04-14", "DBS", "Hybrid");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (772, "2018-04-14", "Scott", "Terreng");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (3043, "2018-04-14", "Trek", "Hybrid");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (1054, "2018-04-14", "Scott", "Hybrid");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (4285, "2018-04-14", "Scott", "Bysykkel");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (2128, "2018-04-14", "Merida", "Hybrid");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (4676, "2018-04-14", "Trek", "Terreng");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (1993, "2018-04-14", "Scott", "Hybrid");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (2292, "2018-04-14", "DBS", "Bysykkel");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (2067, "2018-04-14", "DBS", "Hybrid");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (4390, "2018-04-14", "DBS", "Terreng");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (3122, "2018-04-14", "Merida", "Landevei");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (4562, "2018-04-14", "Trek", "Bysykkel");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (3065, "2018-04-14", "DBS", "Hybrid");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (2820, "2018-04-14", "Trek", "Hybrid");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (3397, "2018-04-14", "DBS", "Bysykkel");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (1225, "2018-04-14", "DBS", "Hybrid");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (2266, "2018-04-14", "DBS", "Terreng");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (3482, "2018-04-14", "Trek", "Landevei");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (4631, "2018-04-14", "Scott", "Landevei");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (3735, "2018-04-14", "Merida", "Landevei");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (636, "2018-04-14", "Merida", "Landevei");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (4703, "2018-04-14", "Merida", "Terreng");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (4064, "2018-04-14", "Merida", "Landevei");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (683, "2018-04-14", "DBS", "Bysykkel");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (3190, "2018-04-14", "Trek", "Landevei");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (627, "2018-04-14", "Merida", "Hybrid");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (988, "2018-04-14", "Merida", "Landevei");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (1584, "2018-04-14", "DBS", "Bysykkel");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (3142, "2018-04-14", "Scott", "Hybrid");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (4508, "2018-04-14", "Scott", "Bysykkel");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (4089, "2018-04-14", "Merida", "Hybrid");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (874, "2018-04-14", "Trek", "Landevei");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (2143, "2018-04-14", "Scott", "Terreng");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (3072, "2018-04-14", "Scott", "Terreng");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (950, "2018-04-14", "Scott", "Bysykkel");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (3366, "2018-04-14", "Trek", "Hybrid");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (2335, "2018-04-14", "Merida", "Hybrid");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (1841, "2018-04-14", "DBS", "Bysykkel");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (3603, "2018-04-14", "Merida", "Bysykkel");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (704, "2018-04-14", "Trek", "Terreng");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (811, "2018-04-14", "Trek", "Bysykkel");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (1020, "2018-04-14", "Scott", "Landevei");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (714, "2018-04-14", "DBS", "Landevei");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (4569, "2018-04-14", "DBS", "Hybrid");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (2109, "2018-04-14", "DBS", "Hybrid");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (2549, "2018-04-14", "DBS", "Terreng");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (4636, "2018-04-14", "Merida", "Bysykkel");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (2291, "2018-04-14", "Scott", "Bysykkel");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (3754, "2018-04-14", "DBS", "Terreng");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (4024, "2018-04-14", "DBS", "Terreng");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (2952, "2018-04-14", "Trek", "Bysykkel");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (1056, "2018-04-14", "Trek", "Landevei");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (2995, "2018-04-14", "Trek", "Hybrid");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (2982, "2018-04-14", "Merida", "Terreng");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (4898, "2018-04-14", "DBS", "Bysykkel");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (2371, "2018-04-14", "Scott", "Hybrid");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (3746, "2018-04-14", "Scott", "Landevei");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (4074, "2018-04-14", "Scott", "Hybrid");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (4989, "2018-04-14", "Scott", "Landevei");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (2833, "2018-04-14", "Trek", "Terreng");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (4185, "2018-04-14", "Scott", "Bysykkel");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (1047, "2018-04-14", "DBS", "Hybrid");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (3973, "2018-04-14", "Trek", "Bysykkel");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (3209, "2018-04-14", "Trek", "Hybrid");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (831, "2018-04-14", "Trek", "Landevei");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (1188, "2018-04-14", "DBS", "Landevei");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (4347, "2018-04-14", "Scott", "Landevei");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (767, "2018-04-14", "Trek", "Bysykkel");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (1275, "2018-04-14", "Scott", "Landevei");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (4999, "2018-04-14", "Scott", "Landevei");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (2657, "2018-04-14", "Trek", "Landevei");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (2911, "2018-04-14", "DBS", "Bysykkel");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (1618, "2018-04-14", "DBS", "Hybrid");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (556, "2018-04-14", "DBS", "Hybrid");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (4482, "2018-04-14", "Merida", "Landevei");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (1287, "2018-04-14", "DBS", "Bysykkel");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (2234, "2018-04-14", "DBS", "Hybrid");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (1941, "2018-04-14", "DBS", "Landevei");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (3511, "2018-04-14", "DBS", "Hybrid");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (885, "2018-04-14", "Trek", "Landevei");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (4813, "2018-04-14", "Merida", "Terreng");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (2887, "2018-04-14", "DBS", "Landevei");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (2925, "2018-04-14", "Trek", "Landevei");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (4820, "2018-04-14", "Merida", "Bysykkel");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (3335, "2018-04-14", "Merida", "Hybrid");
INSERT INTO bikes (price, purchaseDate, make, type) VALUES (3559, "2018-04-14", "Trek", "Hybrid");

INSERT INTO docking_stations (stationName, maxSlots, latitude, longitude) VALUES ("Østre Moholt-tun 21, 7048 Trondheim, Norway", 50, 63.40949879999999, 10.4361706);
INSERT INTO docking_stations (stationName, maxSlots, latitude, longitude) VALUES ("Lade alle, 7041 Trondheim, Norway", 50, 63.44628489999999, 10.4435013);
INSERT INTO docking_stations (stationName, maxSlots, latitude, longitude) VALUES ("Erling Skakkes gate 49B, 7012 Trondheim, Norway", 50, 63.4290354, 10.3849155);
INSERT INTO docking_stations (stationName, maxSlots, latitude, longitude) VALUES ("Helsepaviljongen, 7034 Trondheim, Norway", 50, 63.415693, 10.410904);
INSERT INTO docking_stations (stationName, maxSlots, latitude, longitude) VALUES ("Nidarøy gate 5, 7030 Trondheim, Norway", 50, 63.4241529, 10.3835346);
INSERT INTO docking_stations (stationName, maxSlots, latitude, longitude) VALUES ("Tankvegen 20A, 7046 Trondheim, Norway", 50, 63.4246109, 10.437476);
INSERT INTO docking_stations (stationName, maxSlots, latitude, longitude) VALUES ("Utsiravegen 10B, 7045 Trondheim, Norway", 50, 63.43086469999999, 10.4438072);
INSERT INTO docking_stations (stationName, maxSlots, latitude, longitude) VALUES ("Oldervegen 1, 7059 Jakobsli, Norway", 50, 63.42176369999999, 10.4950277);
INSERT INTO docking_stations (stationName, maxSlots, latitude, longitude) VALUES ("Nedre Bakklandet 60, 7014 Trondheim, Norway", 50, 63.43212189999999, 10.4067248);
INSERT INTO docking_stations (stationName, maxSlots, latitude, longitude) VALUES ("Mellomila 11, 7018 Trondheim, Norway", 50, 63.4307087, 10.3710536);

INSERT INTO slots (slotID, stationID) VALUES (1, 1);
INSERT INTO slots (slotID, stationID) VALUES (2, 1);
INSERT INTO slots (slotID, stationID) VALUES (3, 1);
INSERT INTO slots (slotID, stationID) VALUES (4, 1);
INSERT INTO slots (slotID, stationID) VALUES (5, 1);
INSERT INTO slots (slotID, stationID) VALUES (6, 1);
INSERT INTO slots (slotID, stationID) VALUES (7, 1);
INSERT INTO slots (slotID, stationID) VALUES (8, 1);
INSERT INTO slots (slotID, stationID) VALUES (9, 1);
INSERT INTO slots (slotID, stationID) VALUES (10, 1);
INSERT INTO slots (slotID, stationID) VALUES (11, 1);
INSERT INTO slots (slotID, stationID) VALUES (12, 1);
INSERT INTO slots (slotID, stationID) VALUES (13, 1);
INSERT INTO slots (slotID, stationID) VALUES (14, 1);
INSERT INTO slots (slotID, stationID) VALUES (15, 1);
INSERT INTO slots (slotID, stationID) VALUES (16, 1);
INSERT INTO slots (slotID, stationID) VALUES (17, 1);
INSERT INTO slots (slotID, stationID) VALUES (18, 1);
INSERT INTO slots (slotID, stationID) VALUES (19, 1);
INSERT INTO slots (slotID, stationID) VALUES (20, 1);
INSERT INTO slots (slotID, stationID) VALUES (21, 1);
INSERT INTO slots (slotID, stationID) VALUES (22, 1);
INSERT INTO slots (slotID, stationID) VALUES (23, 1);
INSERT INTO slots (slotID, stationID) VALUES (24, 1);
INSERT INTO slots (slotID, stationID) VALUES (25, 1);
INSERT INTO slots (slotID, stationID) VALUES (26, 1);
INSERT INTO slots (slotID, stationID) VALUES (27, 1);
INSERT INTO slots (slotID, stationID) VALUES (28, 1);
INSERT INTO slots (slotID, stationID) VALUES (29, 1);
INSERT INTO slots (slotID, stationID) VALUES (30, 1);
INSERT INTO slots (slotID, stationID) VALUES (31, 1);
INSERT INTO slots (slotID, stationID) VALUES (32, 1);
INSERT INTO slots (slotID, stationID) VALUES (33, 1);
INSERT INTO slots (slotID, stationID) VALUES (34, 1);
INSERT INTO slots (slotID, stationID) VALUES (35, 1);
INSERT INTO slots (slotID, stationID) VALUES (36, 1);
INSERT INTO slots (slotID, stationID) VALUES (37, 1);
INSERT INTO slots (slotID, stationID) VALUES (38, 1);
INSERT INTO slots (slotID, stationID) VALUES (39, 1);
INSERT INTO slots (slotID, stationID) VALUES (40, 1);
INSERT INTO slots (slotID, stationID) VALUES (41, 1);
INSERT INTO slots (slotID, stationID) VALUES (42, 1);
INSERT INTO slots (slotID, stationID) VALUES (43, 1);
INSERT INTO slots (slotID, stationID) VALUES (44, 1);
INSERT INTO slots (slotID, stationID) VALUES (45, 1);
INSERT INTO slots (slotID, stationID) VALUES (46, 1);
INSERT INTO slots (slotID, stationID) VALUES (47, 1);
INSERT INTO slots (slotID, stationID) VALUES (48, 1);
INSERT INTO slots (slotID, stationID) VALUES (49, 1);
INSERT INTO slots (slotID, stationID) VALUES (50, 1);
INSERT INTO slots (slotID, stationID) VALUES (51, 1);
INSERT INTO slots (slotID, stationID) VALUES (52, 1);
INSERT INTO slots (slotID, stationID) VALUES (53, 1);
INSERT INTO slots (slotID, stationID) VALUES (54, 1);
INSERT INTO slots (slotID, stationID) VALUES (55, 1);
INSERT INTO slots (slotID, stationID) VALUES (56, 1);
INSERT INTO slots (slotID, stationID) VALUES (57, 1);
INSERT INTO slots (slotID, stationID) VALUES (58, 1);
INSERT INTO slots (slotID, stationID) VALUES (59, 1);
INSERT INTO slots (slotID, stationID) VALUES (60, 1);
INSERT INTO slots (slotID, stationID) VALUES (61, 1);
INSERT INTO slots (slotID, stationID) VALUES (62, 1);
INSERT INTO slots (slotID, stationID) VALUES (63, 1);
INSERT INTO slots (slotID, stationID) VALUES (64, 1);
INSERT INTO slots (slotID, stationID) VALUES (65, 1);
INSERT INTO slots (slotID, stationID) VALUES (66, 1);
INSERT INTO slots (slotID, stationID) VALUES (67, 1);
INSERT INTO slots (slotID, stationID) VALUES (68, 1);
INSERT INTO slots (slotID, stationID) VALUES (69, 1);
INSERT INTO slots (slotID, stationID) VALUES (70, 1);
INSERT INTO slots (slotID, stationID) VALUES (71, 1);
INSERT INTO slots (slotID, stationID) VALUES (72, 1);
INSERT INTO slots (slotID, stationID) VALUES (73, 1);
INSERT INTO slots (slotID, stationID) VALUES (74, 1);
INSERT INTO slots (slotID, stationID) VALUES (75, 1);
INSERT INTO slots (slotID, stationID) VALUES (76, 1);
INSERT INTO slots (slotID, stationID) VALUES (77, 1);
INSERT INTO slots (slotID, stationID) VALUES (78, 1);
INSERT INTO slots (slotID, stationID) VALUES (79, 1);
INSERT INTO slots (slotID, stationID) VALUES (80, 1);
INSERT INTO slots (slotID, stationID) VALUES (81, 1);
INSERT INTO slots (slotID, stationID) VALUES (82, 1);
INSERT INTO slots (slotID, stationID) VALUES (83, 1);
INSERT INTO slots (slotID, stationID) VALUES (84, 1);
INSERT INTO slots (slotID, stationID) VALUES (85, 1);
INSERT INTO slots (slotID, stationID) VALUES (86, 1);
INSERT INTO slots (slotID, stationID) VALUES (87, 1);
INSERT INTO slots (slotID, stationID) VALUES (88, 1);
INSERT INTO slots (slotID, stationID) VALUES (89, 1);
INSERT INTO slots (slotID, stationID) VALUES (90, 1);
INSERT INTO slots (slotID, stationID) VALUES (91, 1);
INSERT INTO slots (slotID, stationID) VALUES (92, 1);
INSERT INTO slots (slotID, stationID) VALUES (93, 1);
INSERT INTO slots (slotID, stationID) VALUES (94, 1);
INSERT INTO slots (slotID, stationID) VALUES (95, 1);
INSERT INTO slots (slotID, stationID) VALUES (96, 1);
INSERT INTO slots (slotID, stationID) VALUES (97, 1);
INSERT INTO slots (slotID, stationID) VALUES (98, 1);
INSERT INTO slots (slotID, stationID) VALUES (99, 1);
INSERT INTO slots (slotID, stationID) VALUES (100, 1);
INSERT INTO slots (slotID, stationID) VALUES (1, 2);
INSERT INTO slots (slotID, stationID) VALUES (2, 2);
INSERT INTO slots (slotID, stationID) VALUES (3, 2);
INSERT INTO slots (slotID, stationID) VALUES (4, 2);
INSERT INTO slots (slotID, stationID) VALUES (5, 2);
INSERT INTO slots (slotID, stationID) VALUES (6, 2);
INSERT INTO slots (slotID, stationID) VALUES (7, 2);
INSERT INTO slots (slotID, stationID) VALUES (8, 2);
INSERT INTO slots (slotID, stationID) VALUES (9, 2);
INSERT INTO slots (slotID, stationID) VALUES (10, 2);
INSERT INTO slots (slotID, stationID) VALUES (11, 2);
INSERT INTO slots (slotID, stationID) VALUES (12, 2);
INSERT INTO slots (slotID, stationID) VALUES (13, 2);
INSERT INTO slots (slotID, stationID) VALUES (14, 2);
INSERT INTO slots (slotID, stationID) VALUES (15, 2);
INSERT INTO slots (slotID, stationID) VALUES (16, 2);
INSERT INTO slots (slotID, stationID) VALUES (17, 2);
INSERT INTO slots (slotID, stationID) VALUES (18, 2);
INSERT INTO slots (slotID, stationID) VALUES (19, 2);
INSERT INTO slots (slotID, stationID) VALUES (20, 2);
INSERT INTO slots (slotID, stationID) VALUES (21, 2);
INSERT INTO slots (slotID, stationID) VALUES (22, 2);
INSERT INTO slots (slotID, stationID) VALUES (23, 2);
INSERT INTO slots (slotID, stationID) VALUES (24, 2);
INSERT INTO slots (slotID, stationID) VALUES (25, 2);
INSERT INTO slots (slotID, stationID) VALUES (26, 2);
INSERT INTO slots (slotID, stationID) VALUES (27, 2);
INSERT INTO slots (slotID, stationID) VALUES (28, 2);
INSERT INTO slots (slotID, stationID) VALUES (29, 2);
INSERT INTO slots (slotID, stationID) VALUES (30, 2);
INSERT INTO slots (slotID, stationID) VALUES (31, 2);
INSERT INTO slots (slotID, stationID) VALUES (32, 2);
INSERT INTO slots (slotID, stationID) VALUES (33, 2);
INSERT INTO slots (slotID, stationID) VALUES (34, 2);
INSERT INTO slots (slotID, stationID) VALUES (35, 2);
INSERT INTO slots (slotID, stationID) VALUES (36, 2);
INSERT INTO slots (slotID, stationID) VALUES (37, 2);
INSERT INTO slots (slotID, stationID) VALUES (38, 2);
INSERT INTO slots (slotID, stationID) VALUES (39, 2);
INSERT INTO slots (slotID, stationID) VALUES (40, 2);
INSERT INTO slots (slotID, stationID) VALUES (41, 2);
INSERT INTO slots (slotID, stationID) VALUES (42, 2);
INSERT INTO slots (slotID, stationID) VALUES (43, 2);
INSERT INTO slots (slotID, stationID) VALUES (44, 2);
INSERT INTO slots (slotID, stationID) VALUES (45, 2);
INSERT INTO slots (slotID, stationID) VALUES (46, 2);
INSERT INTO slots (slotID, stationID) VALUES (47, 2);
INSERT INTO slots (slotID, stationID) VALUES (48, 2);
INSERT INTO slots (slotID, stationID) VALUES (49, 2);
INSERT INTO slots (slotID, stationID) VALUES (50, 2);
INSERT INTO slots (slotID, stationID) VALUES (51, 2);
INSERT INTO slots (slotID, stationID) VALUES (52, 2);
INSERT INTO slots (slotID, stationID) VALUES (53, 2);
INSERT INTO slots (slotID, stationID) VALUES (54, 2);
INSERT INTO slots (slotID, stationID) VALUES (55, 2);
INSERT INTO slots (slotID, stationID) VALUES (56, 2);
INSERT INTO slots (slotID, stationID) VALUES (57, 2);
INSERT INTO slots (slotID, stationID) VALUES (58, 2);
INSERT INTO slots (slotID, stationID) VALUES (59, 2);
INSERT INTO slots (slotID, stationID) VALUES (60, 2);
INSERT INTO slots (slotID, stationID) VALUES (61, 2);
INSERT INTO slots (slotID, stationID) VALUES (62, 2);
INSERT INTO slots (slotID, stationID) VALUES (63, 2);
INSERT INTO slots (slotID, stationID) VALUES (64, 2);
INSERT INTO slots (slotID, stationID) VALUES (65, 2);
INSERT INTO slots (slotID, stationID) VALUES (66, 2);
INSERT INTO slots (slotID, stationID) VALUES (67, 2);
INSERT INTO slots (slotID, stationID) VALUES (68, 2);
INSERT INTO slots (slotID, stationID) VALUES (69, 2);
INSERT INTO slots (slotID, stationID) VALUES (70, 2);
INSERT INTO slots (slotID, stationID) VALUES (71, 2);
INSERT INTO slots (slotID, stationID) VALUES (72, 2);
INSERT INTO slots (slotID, stationID) VALUES (73, 2);
INSERT INTO slots (slotID, stationID) VALUES (74, 2);
INSERT INTO slots (slotID, stationID) VALUES (75, 2);
INSERT INTO slots (slotID, stationID) VALUES (76, 2);
INSERT INTO slots (slotID, stationID) VALUES (77, 2);
INSERT INTO slots (slotID, stationID) VALUES (78, 2);
INSERT INTO slots (slotID, stationID) VALUES (79, 2);
INSERT INTO slots (slotID, stationID) VALUES (80, 2);
INSERT INTO slots (slotID, stationID) VALUES (81, 2);
INSERT INTO slots (slotID, stationID) VALUES (82, 2);
INSERT INTO slots (slotID, stationID) VALUES (83, 2);
INSERT INTO slots (slotID, stationID) VALUES (84, 2);
INSERT INTO slots (slotID, stationID) VALUES (85, 2);
INSERT INTO slots (slotID, stationID) VALUES (86, 2);
INSERT INTO slots (slotID, stationID) VALUES (87, 2);
INSERT INTO slots (slotID, stationID) VALUES (88, 2);
INSERT INTO slots (slotID, stationID) VALUES (89, 2);
INSERT INTO slots (slotID, stationID) VALUES (90, 2);
INSERT INTO slots (slotID, stationID) VALUES (91, 2);
INSERT INTO slots (slotID, stationID) VALUES (92, 2);
INSERT INTO slots (slotID, stationID) VALUES (93, 2);
INSERT INTO slots (slotID, stationID) VALUES (94, 2);
INSERT INTO slots (slotID, stationID) VALUES (95, 2);
INSERT INTO slots (slotID, stationID) VALUES (96, 2);
INSERT INTO slots (slotID, stationID) VALUES (97, 2);
INSERT INTO slots (slotID, stationID) VALUES (98, 2);
INSERT INTO slots (slotID, stationID) VALUES (99, 2);
INSERT INTO slots (slotID, stationID) VALUES (100, 2);
INSERT INTO slots (slotID, stationID) VALUES (1, 3);
INSERT INTO slots (slotID, stationID) VALUES (2, 3);
INSERT INTO slots (slotID, stationID) VALUES (3, 3);
INSERT INTO slots (slotID, stationID) VALUES (4, 3);
INSERT INTO slots (slotID, stationID) VALUES (5, 3);
INSERT INTO slots (slotID, stationID) VALUES (6, 3);
INSERT INTO slots (slotID, stationID) VALUES (7, 3);
INSERT INTO slots (slotID, stationID) VALUES (8, 3);
INSERT INTO slots (slotID, stationID) VALUES (9, 3);
INSERT INTO slots (slotID, stationID) VALUES (10, 3);
INSERT INTO slots (slotID, stationID) VALUES (11, 3);
INSERT INTO slots (slotID, stationID) VALUES (12, 3);
INSERT INTO slots (slotID, stationID) VALUES (13, 3);
INSERT INTO slots (slotID, stationID) VALUES (14, 3);
INSERT INTO slots (slotID, stationID) VALUES (15, 3);
INSERT INTO slots (slotID, stationID) VALUES (16, 3);
INSERT INTO slots (slotID, stationID) VALUES (17, 3);
INSERT INTO slots (slotID, stationID) VALUES (18, 3);
INSERT INTO slots (slotID, stationID) VALUES (19, 3);
INSERT INTO slots (slotID, stationID) VALUES (20, 3);
INSERT INTO slots (slotID, stationID) VALUES (21, 3);
INSERT INTO slots (slotID, stationID) VALUES (22, 3);
INSERT INTO slots (slotID, stationID) VALUES (23, 3);
INSERT INTO slots (slotID, stationID) VALUES (24, 3);
INSERT INTO slots (slotID, stationID) VALUES (25, 3);
INSERT INTO slots (slotID, stationID) VALUES (26, 3);
INSERT INTO slots (slotID, stationID) VALUES (27, 3);
INSERT INTO slots (slotID, stationID) VALUES (28, 3);
INSERT INTO slots (slotID, stationID) VALUES (29, 3);
INSERT INTO slots (slotID, stationID) VALUES (30, 3);
INSERT INTO slots (slotID, stationID) VALUES (31, 3);
INSERT INTO slots (slotID, stationID) VALUES (32, 3);
INSERT INTO slots (slotID, stationID) VALUES (33, 3);
INSERT INTO slots (slotID, stationID) VALUES (34, 3);
INSERT INTO slots (slotID, stationID) VALUES (35, 3);
INSERT INTO slots (slotID, stationID) VALUES (36, 3);
INSERT INTO slots (slotID, stationID) VALUES (37, 3);
INSERT INTO slots (slotID, stationID) VALUES (38, 3);
INSERT INTO slots (slotID, stationID) VALUES (39, 3);
INSERT INTO slots (slotID, stationID) VALUES (40, 3);
INSERT INTO slots (slotID, stationID) VALUES (41, 3);
INSERT INTO slots (slotID, stationID) VALUES (42, 3);
INSERT INTO slots (slotID, stationID) VALUES (43, 3);
INSERT INTO slots (slotID, stationID) VALUES (44, 3);
INSERT INTO slots (slotID, stationID) VALUES (45, 3);
INSERT INTO slots (slotID, stationID) VALUES (46, 3);
INSERT INTO slots (slotID, stationID) VALUES (47, 3);
INSERT INTO slots (slotID, stationID) VALUES (48, 3);
INSERT INTO slots (slotID, stationID) VALUES (49, 3);
INSERT INTO slots (slotID, stationID) VALUES (50, 3);
INSERT INTO slots (slotID, stationID) VALUES (51, 3);
INSERT INTO slots (slotID, stationID) VALUES (52, 3);
INSERT INTO slots (slotID, stationID) VALUES (53, 3);
INSERT INTO slots (slotID, stationID) VALUES (54, 3);
INSERT INTO slots (slotID, stationID) VALUES (55, 3);
INSERT INTO slots (slotID, stationID) VALUES (56, 3);
INSERT INTO slots (slotID, stationID) VALUES (57, 3);
INSERT INTO slots (slotID, stationID) VALUES (58, 3);
INSERT INTO slots (slotID, stationID) VALUES (59, 3);
INSERT INTO slots (slotID, stationID) VALUES (60, 3);
INSERT INTO slots (slotID, stationID) VALUES (61, 3);
INSERT INTO slots (slotID, stationID) VALUES (62, 3);
INSERT INTO slots (slotID, stationID) VALUES (63, 3);
INSERT INTO slots (slotID, stationID) VALUES (64, 3);
INSERT INTO slots (slotID, stationID) VALUES (65, 3);
INSERT INTO slots (slotID, stationID) VALUES (66, 3);
INSERT INTO slots (slotID, stationID) VALUES (67, 3);
INSERT INTO slots (slotID, stationID) VALUES (68, 3);
INSERT INTO slots (slotID, stationID) VALUES (69, 3);
INSERT INTO slots (slotID, stationID) VALUES (70, 3);
INSERT INTO slots (slotID, stationID) VALUES (71, 3);
INSERT INTO slots (slotID, stationID) VALUES (72, 3);
INSERT INTO slots (slotID, stationID) VALUES (73, 3);
INSERT INTO slots (slotID, stationID) VALUES (74, 3);
INSERT INTO slots (slotID, stationID) VALUES (75, 3);
INSERT INTO slots (slotID, stationID) VALUES (76, 3);
INSERT INTO slots (slotID, stationID) VALUES (77, 3);
INSERT INTO slots (slotID, stationID) VALUES (78, 3);
INSERT INTO slots (slotID, stationID) VALUES (79, 3);
INSERT INTO slots (slotID, stationID) VALUES (80, 3);
INSERT INTO slots (slotID, stationID) VALUES (81, 3);
INSERT INTO slots (slotID, stationID) VALUES (82, 3);
INSERT INTO slots (slotID, stationID) VALUES (83, 3);
INSERT INTO slots (slotID, stationID) VALUES (84, 3);
INSERT INTO slots (slotID, stationID) VALUES (85, 3);
INSERT INTO slots (slotID, stationID) VALUES (86, 3);
INSERT INTO slots (slotID, stationID) VALUES (87, 3);
INSERT INTO slots (slotID, stationID) VALUES (88, 3);
INSERT INTO slots (slotID, stationID) VALUES (89, 3);
INSERT INTO slots (slotID, stationID) VALUES (90, 3);
INSERT INTO slots (slotID, stationID) VALUES (91, 3);
INSERT INTO slots (slotID, stationID) VALUES (92, 3);
INSERT INTO slots (slotID, stationID) VALUES (93, 3);
INSERT INTO slots (slotID, stationID) VALUES (94, 3);
INSERT INTO slots (slotID, stationID) VALUES (95, 3);
INSERT INTO slots (slotID, stationID) VALUES (96, 3);
INSERT INTO slots (slotID, stationID) VALUES (97, 3);
INSERT INTO slots (slotID, stationID) VALUES (98, 3);
INSERT INTO slots (slotID, stationID) VALUES (99, 3);
INSERT INTO slots (slotID, stationID) VALUES (100, 3);
INSERT INTO slots (slotID, stationID) VALUES (1, 4);
INSERT INTO slots (slotID, stationID) VALUES (2, 4);
INSERT INTO slots (slotID, stationID) VALUES (3, 4);
INSERT INTO slots (slotID, stationID) VALUES (4, 4);
INSERT INTO slots (slotID, stationID) VALUES (5, 4);
INSERT INTO slots (slotID, stationID) VALUES (6, 4);
INSERT INTO slots (slotID, stationID) VALUES (7, 4);
INSERT INTO slots (slotID, stationID) VALUES (8, 4);
INSERT INTO slots (slotID, stationID) VALUES (9, 4);
INSERT INTO slots (slotID, stationID) VALUES (10, 4);
INSERT INTO slots (slotID, stationID) VALUES (11, 4);
INSERT INTO slots (slotID, stationID) VALUES (12, 4);
INSERT INTO slots (slotID, stationID) VALUES (13, 4);
INSERT INTO slots (slotID, stationID) VALUES (14, 4);
INSERT INTO slots (slotID, stationID) VALUES (15, 4);
INSERT INTO slots (slotID, stationID) VALUES (16, 4);
INSERT INTO slots (slotID, stationID) VALUES (17, 4);
INSERT INTO slots (slotID, stationID) VALUES (18, 4);
INSERT INTO slots (slotID, stationID) VALUES (19, 4);
INSERT INTO slots (slotID, stationID) VALUES (20, 4);
INSERT INTO slots (slotID, stationID) VALUES (21, 4);
INSERT INTO slots (slotID, stationID) VALUES (22, 4);
INSERT INTO slots (slotID, stationID) VALUES (23, 4);
INSERT INTO slots (slotID, stationID) VALUES (24, 4);
INSERT INTO slots (slotID, stationID) VALUES (25, 4);
INSERT INTO slots (slotID, stationID) VALUES (26, 4);
INSERT INTO slots (slotID, stationID) VALUES (27, 4);
INSERT INTO slots (slotID, stationID) VALUES (28, 4);
INSERT INTO slots (slotID, stationID) VALUES (29, 4);
INSERT INTO slots (slotID, stationID) VALUES (30, 4);
INSERT INTO slots (slotID, stationID) VALUES (31, 4);
INSERT INTO slots (slotID, stationID) VALUES (32, 4);
INSERT INTO slots (slotID, stationID) VALUES (33, 4);
INSERT INTO slots (slotID, stationID) VALUES (34, 4);
INSERT INTO slots (slotID, stationID) VALUES (35, 4);
INSERT INTO slots (slotID, stationID) VALUES (36, 4);
INSERT INTO slots (slotID, stationID) VALUES (37, 4);
INSERT INTO slots (slotID, stationID) VALUES (38, 4);
INSERT INTO slots (slotID, stationID) VALUES (39, 4);
INSERT INTO slots (slotID, stationID) VALUES (40, 4);
INSERT INTO slots (slotID, stationID) VALUES (41, 4);
INSERT INTO slots (slotID, stationID) VALUES (42, 4);
INSERT INTO slots (slotID, stationID) VALUES (43, 4);
INSERT INTO slots (slotID, stationID) VALUES (44, 4);
INSERT INTO slots (slotID, stationID) VALUES (45, 4);
INSERT INTO slots (slotID, stationID) VALUES (46, 4);
INSERT INTO slots (slotID, stationID) VALUES (47, 4);
INSERT INTO slots (slotID, stationID) VALUES (48, 4);
INSERT INTO slots (slotID, stationID) VALUES (49, 4);
INSERT INTO slots (slotID, stationID) VALUES (50, 4);
INSERT INTO slots (slotID, stationID) VALUES (51, 4);
INSERT INTO slots (slotID, stationID) VALUES (52, 4);
INSERT INTO slots (slotID, stationID) VALUES (53, 4);
INSERT INTO slots (slotID, stationID) VALUES (54, 4);
INSERT INTO slots (slotID, stationID) VALUES (55, 4);
INSERT INTO slots (slotID, stationID) VALUES (56, 4);
INSERT INTO slots (slotID, stationID) VALUES (57, 4);
INSERT INTO slots (slotID, stationID) VALUES (58, 4);
INSERT INTO slots (slotID, stationID) VALUES (59, 4);
INSERT INTO slots (slotID, stationID) VALUES (60, 4);
INSERT INTO slots (slotID, stationID) VALUES (61, 4);
INSERT INTO slots (slotID, stationID) VALUES (62, 4);
INSERT INTO slots (slotID, stationID) VALUES (63, 4);
INSERT INTO slots (slotID, stationID) VALUES (64, 4);
INSERT INTO slots (slotID, stationID) VALUES (65, 4);
INSERT INTO slots (slotID, stationID) VALUES (66, 4);
INSERT INTO slots (slotID, stationID) VALUES (67, 4);
INSERT INTO slots (slotID, stationID) VALUES (68, 4);
INSERT INTO slots (slotID, stationID) VALUES (69, 4);
INSERT INTO slots (slotID, stationID) VALUES (70, 4);
INSERT INTO slots (slotID, stationID) VALUES (71, 4);
INSERT INTO slots (slotID, stationID) VALUES (72, 4);
INSERT INTO slots (slotID, stationID) VALUES (73, 4);
INSERT INTO slots (slotID, stationID) VALUES (74, 4);
INSERT INTO slots (slotID, stationID) VALUES (75, 4);
INSERT INTO slots (slotID, stationID) VALUES (76, 4);
INSERT INTO slots (slotID, stationID) VALUES (77, 4);
INSERT INTO slots (slotID, stationID) VALUES (78, 4);
INSERT INTO slots (slotID, stationID) VALUES (79, 4);
INSERT INTO slots (slotID, stationID) VALUES (80, 4);
INSERT INTO slots (slotID, stationID) VALUES (81, 4);
INSERT INTO slots (slotID, stationID) VALUES (82, 4);
INSERT INTO slots (slotID, stationID) VALUES (83, 4);
INSERT INTO slots (slotID, stationID) VALUES (84, 4);
INSERT INTO slots (slotID, stationID) VALUES (85, 4);
INSERT INTO slots (slotID, stationID) VALUES (86, 4);
INSERT INTO slots (slotID, stationID) VALUES (87, 4);
INSERT INTO slots (slotID, stationID) VALUES (88, 4);
INSERT INTO slots (slotID, stationID) VALUES (89, 4);
INSERT INTO slots (slotID, stationID) VALUES (90, 4);
INSERT INTO slots (slotID, stationID) VALUES (91, 4);
INSERT INTO slots (slotID, stationID) VALUES (92, 4);
INSERT INTO slots (slotID, stationID) VALUES (93, 4);
INSERT INTO slots (slotID, stationID) VALUES (94, 4);
INSERT INTO slots (slotID, stationID) VALUES (95, 4);
INSERT INTO slots (slotID, stationID) VALUES (96, 4);
INSERT INTO slots (slotID, stationID) VALUES (97, 4);
INSERT INTO slots (slotID, stationID) VALUES (98, 4);
INSERT INTO slots (slotID, stationID) VALUES (99, 4);
INSERT INTO slots (slotID, stationID) VALUES (100, 4);
INSERT INTO slots (slotID, stationID) VALUES (1, 5);
INSERT INTO slots (slotID, stationID) VALUES (2, 5);
INSERT INTO slots (slotID, stationID) VALUES (3, 5);
INSERT INTO slots (slotID, stationID) VALUES (4, 5);
INSERT INTO slots (slotID, stationID) VALUES (5, 5);
INSERT INTO slots (slotID, stationID) VALUES (6, 5);
INSERT INTO slots (slotID, stationID) VALUES (7, 5);
INSERT INTO slots (slotID, stationID) VALUES (8, 5);
INSERT INTO slots (slotID, stationID) VALUES (9, 5);
INSERT INTO slots (slotID, stationID) VALUES (10, 5);
INSERT INTO slots (slotID, stationID) VALUES (11, 5);
INSERT INTO slots (slotID, stationID) VALUES (12, 5);
INSERT INTO slots (slotID, stationID) VALUES (13, 5);
INSERT INTO slots (slotID, stationID) VALUES (14, 5);
INSERT INTO slots (slotID, stationID) VALUES (15, 5);
INSERT INTO slots (slotID, stationID) VALUES (16, 5);
INSERT INTO slots (slotID, stationID) VALUES (17, 5);
INSERT INTO slots (slotID, stationID) VALUES (18, 5);
INSERT INTO slots (slotID, stationID) VALUES (19, 5);
INSERT INTO slots (slotID, stationID) VALUES (20, 5);
INSERT INTO slots (slotID, stationID) VALUES (21, 5);
INSERT INTO slots (slotID, stationID) VALUES (22, 5);
INSERT INTO slots (slotID, stationID) VALUES (23, 5);
INSERT INTO slots (slotID, stationID) VALUES (24, 5);
INSERT INTO slots (slotID, stationID) VALUES (25, 5);
INSERT INTO slots (slotID, stationID) VALUES (26, 5);
INSERT INTO slots (slotID, stationID) VALUES (27, 5);
INSERT INTO slots (slotID, stationID) VALUES (28, 5);
INSERT INTO slots (slotID, stationID) VALUES (29, 5);
INSERT INTO slots (slotID, stationID) VALUES (30, 5);
INSERT INTO slots (slotID, stationID) VALUES (31, 5);
INSERT INTO slots (slotID, stationID) VALUES (32, 5);
INSERT INTO slots (slotID, stationID) VALUES (33, 5);
INSERT INTO slots (slotID, stationID) VALUES (34, 5);
INSERT INTO slots (slotID, stationID) VALUES (35, 5);
INSERT INTO slots (slotID, stationID) VALUES (36, 5);
INSERT INTO slots (slotID, stationID) VALUES (37, 5);
INSERT INTO slots (slotID, stationID) VALUES (38, 5);
INSERT INTO slots (slotID, stationID) VALUES (39, 5);
INSERT INTO slots (slotID, stationID) VALUES (40, 5);
INSERT INTO slots (slotID, stationID) VALUES (41, 5);
INSERT INTO slots (slotID, stationID) VALUES (42, 5);
INSERT INTO slots (slotID, stationID) VALUES (43, 5);
INSERT INTO slots (slotID, stationID) VALUES (44, 5);
INSERT INTO slots (slotID, stationID) VALUES (45, 5);
INSERT INTO slots (slotID, stationID) VALUES (46, 5);
INSERT INTO slots (slotID, stationID) VALUES (47, 5);
INSERT INTO slots (slotID, stationID) VALUES (48, 5);
INSERT INTO slots (slotID, stationID) VALUES (49, 5);
INSERT INTO slots (slotID, stationID) VALUES (50, 5);
INSERT INTO slots (slotID, stationID) VALUES (51, 5);
INSERT INTO slots (slotID, stationID) VALUES (52, 5);
INSERT INTO slots (slotID, stationID) VALUES (53, 5);
INSERT INTO slots (slotID, stationID) VALUES (54, 5);
INSERT INTO slots (slotID, stationID) VALUES (55, 5);
INSERT INTO slots (slotID, stationID) VALUES (56, 5);
INSERT INTO slots (slotID, stationID) VALUES (57, 5);
INSERT INTO slots (slotID, stationID) VALUES (58, 5);
INSERT INTO slots (slotID, stationID) VALUES (59, 5);
INSERT INTO slots (slotID, stationID) VALUES (60, 5);
INSERT INTO slots (slotID, stationID) VALUES (61, 5);
INSERT INTO slots (slotID, stationID) VALUES (62, 5);
INSERT INTO slots (slotID, stationID) VALUES (63, 5);
INSERT INTO slots (slotID, stationID) VALUES (64, 5);
INSERT INTO slots (slotID, stationID) VALUES (65, 5);
INSERT INTO slots (slotID, stationID) VALUES (66, 5);
INSERT INTO slots (slotID, stationID) VALUES (67, 5);
INSERT INTO slots (slotID, stationID) VALUES (68, 5);
INSERT INTO slots (slotID, stationID) VALUES (69, 5);
INSERT INTO slots (slotID, stationID) VALUES (70, 5);
INSERT INTO slots (slotID, stationID) VALUES (71, 5);
INSERT INTO slots (slotID, stationID) VALUES (72, 5);
INSERT INTO slots (slotID, stationID) VALUES (73, 5);
INSERT INTO slots (slotID, stationID) VALUES (74, 5);
INSERT INTO slots (slotID, stationID) VALUES (75, 5);
INSERT INTO slots (slotID, stationID) VALUES (76, 5);
INSERT INTO slots (slotID, stationID) VALUES (77, 5);
INSERT INTO slots (slotID, stationID) VALUES (78, 5);
INSERT INTO slots (slotID, stationID) VALUES (79, 5);
INSERT INTO slots (slotID, stationID) VALUES (80, 5);
INSERT INTO slots (slotID, stationID) VALUES (81, 5);
INSERT INTO slots (slotID, stationID) VALUES (82, 5);
INSERT INTO slots (slotID, stationID) VALUES (83, 5);
INSERT INTO slots (slotID, stationID) VALUES (84, 5);
INSERT INTO slots (slotID, stationID) VALUES (85, 5);
INSERT INTO slots (slotID, stationID) VALUES (86, 5);
INSERT INTO slots (slotID, stationID) VALUES (87, 5);
INSERT INTO slots (slotID, stationID) VALUES (88, 5);
INSERT INTO slots (slotID, stationID) VALUES (89, 5);
INSERT INTO slots (slotID, stationID) VALUES (90, 5);
INSERT INTO slots (slotID, stationID) VALUES (91, 5);
INSERT INTO slots (slotID, stationID) VALUES (92, 5);
INSERT INTO slots (slotID, stationID) VALUES (93, 5);
INSERT INTO slots (slotID, stationID) VALUES (94, 5);
INSERT INTO slots (slotID, stationID) VALUES (95, 5);
INSERT INTO slots (slotID, stationID) VALUES (96, 5);
INSERT INTO slots (slotID, stationID) VALUES (97, 5);
INSERT INTO slots (slotID, stationID) VALUES (98, 5);
INSERT INTO slots (slotID, stationID) VALUES (99, 5);
INSERT INTO slots (slotID, stationID) VALUES (100, 5);
INSERT INTO slots (slotID, stationID) VALUES (1, 6);
INSERT INTO slots (slotID, stationID) VALUES (2, 6);
INSERT INTO slots (slotID, stationID) VALUES (3, 6);
INSERT INTO slots (slotID, stationID) VALUES (4, 6);
INSERT INTO slots (slotID, stationID) VALUES (5, 6);
INSERT INTO slots (slotID, stationID) VALUES (6, 6);
INSERT INTO slots (slotID, stationID) VALUES (7, 6);
INSERT INTO slots (slotID, stationID) VALUES (8, 6);
INSERT INTO slots (slotID, stationID) VALUES (9, 6);
INSERT INTO slots (slotID, stationID) VALUES (10, 6);
INSERT INTO slots (slotID, stationID) VALUES (11, 6);
INSERT INTO slots (slotID, stationID) VALUES (12, 6);
INSERT INTO slots (slotID, stationID) VALUES (13, 6);
INSERT INTO slots (slotID, stationID) VALUES (14, 6);
INSERT INTO slots (slotID, stationID) VALUES (15, 6);
INSERT INTO slots (slotID, stationID) VALUES (16, 6);
INSERT INTO slots (slotID, stationID) VALUES (17, 6);
INSERT INTO slots (slotID, stationID) VALUES (18, 6);
INSERT INTO slots (slotID, stationID) VALUES (19, 6);
INSERT INTO slots (slotID, stationID) VALUES (20, 6);
INSERT INTO slots (slotID, stationID) VALUES (21, 6);
INSERT INTO slots (slotID, stationID) VALUES (22, 6);
INSERT INTO slots (slotID, stationID) VALUES (23, 6);
INSERT INTO slots (slotID, stationID) VALUES (24, 6);
INSERT INTO slots (slotID, stationID) VALUES (25, 6);
INSERT INTO slots (slotID, stationID) VALUES (26, 6);
INSERT INTO slots (slotID, stationID) VALUES (27, 6);
INSERT INTO slots (slotID, stationID) VALUES (28, 6);
INSERT INTO slots (slotID, stationID) VALUES (29, 6);
INSERT INTO slots (slotID, stationID) VALUES (30, 6);
INSERT INTO slots (slotID, stationID) VALUES (31, 6);
INSERT INTO slots (slotID, stationID) VALUES (32, 6);
INSERT INTO slots (slotID, stationID) VALUES (33, 6);
INSERT INTO slots (slotID, stationID) VALUES (34, 6);
INSERT INTO slots (slotID, stationID) VALUES (35, 6);
INSERT INTO slots (slotID, stationID) VALUES (36, 6);
INSERT INTO slots (slotID, stationID) VALUES (37, 6);
INSERT INTO slots (slotID, stationID) VALUES (38, 6);
INSERT INTO slots (slotID, stationID) VALUES (39, 6);
INSERT INTO slots (slotID, stationID) VALUES (40, 6);
INSERT INTO slots (slotID, stationID) VALUES (41, 6);
INSERT INTO slots (slotID, stationID) VALUES (42, 6);
INSERT INTO slots (slotID, stationID) VALUES (43, 6);
INSERT INTO slots (slotID, stationID) VALUES (44, 6);
INSERT INTO slots (slotID, stationID) VALUES (45, 6);
INSERT INTO slots (slotID, stationID) VALUES (46, 6);
INSERT INTO slots (slotID, stationID) VALUES (47, 6);
INSERT INTO slots (slotID, stationID) VALUES (48, 6);
INSERT INTO slots (slotID, stationID) VALUES (49, 6);
INSERT INTO slots (slotID, stationID) VALUES (50, 6);
INSERT INTO slots (slotID, stationID) VALUES (51, 6);
INSERT INTO slots (slotID, stationID) VALUES (52, 6);
INSERT INTO slots (slotID, stationID) VALUES (53, 6);
INSERT INTO slots (slotID, stationID) VALUES (54, 6);
INSERT INTO slots (slotID, stationID) VALUES (55, 6);
INSERT INTO slots (slotID, stationID) VALUES (56, 6);
INSERT INTO slots (slotID, stationID) VALUES (57, 6);
INSERT INTO slots (slotID, stationID) VALUES (58, 6);
INSERT INTO slots (slotID, stationID) VALUES (59, 6);
INSERT INTO slots (slotID, stationID) VALUES (60, 6);
INSERT INTO slots (slotID, stationID) VALUES (61, 6);
INSERT INTO slots (slotID, stationID) VALUES (62, 6);
INSERT INTO slots (slotID, stationID) VALUES (63, 6);
INSERT INTO slots (slotID, stationID) VALUES (64, 6);
INSERT INTO slots (slotID, stationID) VALUES (65, 6);
INSERT INTO slots (slotID, stationID) VALUES (66, 6);
INSERT INTO slots (slotID, stationID) VALUES (67, 6);
INSERT INTO slots (slotID, stationID) VALUES (68, 6);
INSERT INTO slots (slotID, stationID) VALUES (69, 6);
INSERT INTO slots (slotID, stationID) VALUES (70, 6);
INSERT INTO slots (slotID, stationID) VALUES (71, 6);
INSERT INTO slots (slotID, stationID) VALUES (72, 6);
INSERT INTO slots (slotID, stationID) VALUES (73, 6);
INSERT INTO slots (slotID, stationID) VALUES (74, 6);
INSERT INTO slots (slotID, stationID) VALUES (75, 6);
INSERT INTO slots (slotID, stationID) VALUES (76, 6);
INSERT INTO slots (slotID, stationID) VALUES (77, 6);
INSERT INTO slots (slotID, stationID) VALUES (78, 6);
INSERT INTO slots (slotID, stationID) VALUES (79, 6);
INSERT INTO slots (slotID, stationID) VALUES (80, 6);
INSERT INTO slots (slotID, stationID) VALUES (81, 6);
INSERT INTO slots (slotID, stationID) VALUES (82, 6);
INSERT INTO slots (slotID, stationID) VALUES (83, 6);
INSERT INTO slots (slotID, stationID) VALUES (84, 6);
INSERT INTO slots (slotID, stationID) VALUES (85, 6);
INSERT INTO slots (slotID, stationID) VALUES (86, 6);
INSERT INTO slots (slotID, stationID) VALUES (87, 6);
INSERT INTO slots (slotID, stationID) VALUES (88, 6);
INSERT INTO slots (slotID, stationID) VALUES (89, 6);
INSERT INTO slots (slotID, stationID) VALUES (90, 6);
INSERT INTO slots (slotID, stationID) VALUES (91, 6);
INSERT INTO slots (slotID, stationID) VALUES (92, 6);
INSERT INTO slots (slotID, stationID) VALUES (93, 6);
INSERT INTO slots (slotID, stationID) VALUES (94, 6);
INSERT INTO slots (slotID, stationID) VALUES (95, 6);
INSERT INTO slots (slotID, stationID) VALUES (96, 6);
INSERT INTO slots (slotID, stationID) VALUES (97, 6);
INSERT INTO slots (slotID, stationID) VALUES (98, 6);
INSERT INTO slots (slotID, stationID) VALUES (99, 6);
INSERT INTO slots (slotID, stationID) VALUES (100, 6);
INSERT INTO slots (slotID, stationID) VALUES (1, 7);
INSERT INTO slots (slotID, stationID) VALUES (2, 7);
INSERT INTO slots (slotID, stationID) VALUES (3, 7);
INSERT INTO slots (slotID, stationID) VALUES (4, 7);
INSERT INTO slots (slotID, stationID) VALUES (5, 7);
INSERT INTO slots (slotID, stationID) VALUES (6, 7);
INSERT INTO slots (slotID, stationID) VALUES (7, 7);
INSERT INTO slots (slotID, stationID) VALUES (8, 7);
INSERT INTO slots (slotID, stationID) VALUES (9, 7);
INSERT INTO slots (slotID, stationID) VALUES (10, 7);
INSERT INTO slots (slotID, stationID) VALUES (11, 7);
INSERT INTO slots (slotID, stationID) VALUES (12, 7);
INSERT INTO slots (slotID, stationID) VALUES (13, 7);
INSERT INTO slots (slotID, stationID) VALUES (14, 7);
INSERT INTO slots (slotID, stationID) VALUES (15, 7);
INSERT INTO slots (slotID, stationID) VALUES (16, 7);
INSERT INTO slots (slotID, stationID) VALUES (17, 7);
INSERT INTO slots (slotID, stationID) VALUES (18, 7);
INSERT INTO slots (slotID, stationID) VALUES (19, 7);
INSERT INTO slots (slotID, stationID) VALUES (20, 7);
INSERT INTO slots (slotID, stationID) VALUES (21, 7);
INSERT INTO slots (slotID, stationID) VALUES (22, 7);
INSERT INTO slots (slotID, stationID) VALUES (23, 7);
INSERT INTO slots (slotID, stationID) VALUES (24, 7);
INSERT INTO slots (slotID, stationID) VALUES (25, 7);
INSERT INTO slots (slotID, stationID) VALUES (26, 7);
INSERT INTO slots (slotID, stationID) VALUES (27, 7);
INSERT INTO slots (slotID, stationID) VALUES (28, 7);
INSERT INTO slots (slotID, stationID) VALUES (29, 7);
INSERT INTO slots (slotID, stationID) VALUES (30, 7);
INSERT INTO slots (slotID, stationID) VALUES (31, 7);
INSERT INTO slots (slotID, stationID) VALUES (32, 7);
INSERT INTO slots (slotID, stationID) VALUES (33, 7);
INSERT INTO slots (slotID, stationID) VALUES (34, 7);
INSERT INTO slots (slotID, stationID) VALUES (35, 7);
INSERT INTO slots (slotID, stationID) VALUES (36, 7);
INSERT INTO slots (slotID, stationID) VALUES (37, 7);
INSERT INTO slots (slotID, stationID) VALUES (38, 7);
INSERT INTO slots (slotID, stationID) VALUES (39, 7);
INSERT INTO slots (slotID, stationID) VALUES (40, 7);
INSERT INTO slots (slotID, stationID) VALUES (41, 7);
INSERT INTO slots (slotID, stationID) VALUES (42, 7);
INSERT INTO slots (slotID, stationID) VALUES (43, 7);
INSERT INTO slots (slotID, stationID) VALUES (44, 7);
INSERT INTO slots (slotID, stationID) VALUES (45, 7);
INSERT INTO slots (slotID, stationID) VALUES (46, 7);
INSERT INTO slots (slotID, stationID) VALUES (47, 7);
INSERT INTO slots (slotID, stationID) VALUES (48, 7);
INSERT INTO slots (slotID, stationID) VALUES (49, 7);
INSERT INTO slots (slotID, stationID) VALUES (50, 7);
INSERT INTO slots (slotID, stationID) VALUES (51, 7);
INSERT INTO slots (slotID, stationID) VALUES (52, 7);
INSERT INTO slots (slotID, stationID) VALUES (53, 7);
INSERT INTO slots (slotID, stationID) VALUES (54, 7);
INSERT INTO slots (slotID, stationID) VALUES (55, 7);
INSERT INTO slots (slotID, stationID) VALUES (56, 7);
INSERT INTO slots (slotID, stationID) VALUES (57, 7);
INSERT INTO slots (slotID, stationID) VALUES (58, 7);
INSERT INTO slots (slotID, stationID) VALUES (59, 7);
INSERT INTO slots (slotID, stationID) VALUES (60, 7);
INSERT INTO slots (slotID, stationID) VALUES (61, 7);
INSERT INTO slots (slotID, stationID) VALUES (62, 7);
INSERT INTO slots (slotID, stationID) VALUES (63, 7);
INSERT INTO slots (slotID, stationID) VALUES (64, 7);
INSERT INTO slots (slotID, stationID) VALUES (65, 7);
INSERT INTO slots (slotID, stationID) VALUES (66, 7);
INSERT INTO slots (slotID, stationID) VALUES (67, 7);
INSERT INTO slots (slotID, stationID) VALUES (68, 7);
INSERT INTO slots (slotID, stationID) VALUES (69, 7);
INSERT INTO slots (slotID, stationID) VALUES (70, 7);
INSERT INTO slots (slotID, stationID) VALUES (71, 7);
INSERT INTO slots (slotID, stationID) VALUES (72, 7);
INSERT INTO slots (slotID, stationID) VALUES (73, 7);
INSERT INTO slots (slotID, stationID) VALUES (74, 7);
INSERT INTO slots (slotID, stationID) VALUES (75, 7);
INSERT INTO slots (slotID, stationID) VALUES (76, 7);
INSERT INTO slots (slotID, stationID) VALUES (77, 7);
INSERT INTO slots (slotID, stationID) VALUES (78, 7);
INSERT INTO slots (slotID, stationID) VALUES (79, 7);
INSERT INTO slots (slotID, stationID) VALUES (80, 7);
INSERT INTO slots (slotID, stationID) VALUES (81, 7);
INSERT INTO slots (slotID, stationID) VALUES (82, 7);
INSERT INTO slots (slotID, stationID) VALUES (83, 7);
INSERT INTO slots (slotID, stationID) VALUES (84, 7);
INSERT INTO slots (slotID, stationID) VALUES (85, 7);
INSERT INTO slots (slotID, stationID) VALUES (86, 7);
INSERT INTO slots (slotID, stationID) VALUES (87, 7);
INSERT INTO slots (slotID, stationID) VALUES (88, 7);
INSERT INTO slots (slotID, stationID) VALUES (89, 7);
INSERT INTO slots (slotID, stationID) VALUES (90, 7);
INSERT INTO slots (slotID, stationID) VALUES (91, 7);
INSERT INTO slots (slotID, stationID) VALUES (92, 7);
INSERT INTO slots (slotID, stationID) VALUES (93, 7);
INSERT INTO slots (slotID, stationID) VALUES (94, 7);
INSERT INTO slots (slotID, stationID) VALUES (95, 7);
INSERT INTO slots (slotID, stationID) VALUES (96, 7);
INSERT INTO slots (slotID, stationID) VALUES (97, 7);
INSERT INTO slots (slotID, stationID) VALUES (98, 7);
INSERT INTO slots (slotID, stationID) VALUES (99, 7);
INSERT INTO slots (slotID, stationID) VALUES (100, 7);
INSERT INTO slots (slotID, stationID) VALUES (1, 8);
INSERT INTO slots (slotID, stationID) VALUES (2, 8);
INSERT INTO slots (slotID, stationID) VALUES (3, 8);
INSERT INTO slots (slotID, stationID) VALUES (4, 8);
INSERT INTO slots (slotID, stationID) VALUES (5, 8);
INSERT INTO slots (slotID, stationID) VALUES (6, 8);
INSERT INTO slots (slotID, stationID) VALUES (7, 8);
INSERT INTO slots (slotID, stationID) VALUES (8, 8);
INSERT INTO slots (slotID, stationID) VALUES (9, 8);
INSERT INTO slots (slotID, stationID) VALUES (10, 8);
INSERT INTO slots (slotID, stationID) VALUES (11, 8);
INSERT INTO slots (slotID, stationID) VALUES (12, 8);
INSERT INTO slots (slotID, stationID) VALUES (13, 8);
INSERT INTO slots (slotID, stationID) VALUES (14, 8);
INSERT INTO slots (slotID, stationID) VALUES (15, 8);
INSERT INTO slots (slotID, stationID) VALUES (16, 8);
INSERT INTO slots (slotID, stationID) VALUES (17, 8);
INSERT INTO slots (slotID, stationID) VALUES (18, 8);
INSERT INTO slots (slotID, stationID) VALUES (19, 8);
INSERT INTO slots (slotID, stationID) VALUES (20, 8);
INSERT INTO slots (slotID, stationID) VALUES (21, 8);
INSERT INTO slots (slotID, stationID) VALUES (22, 8);
INSERT INTO slots (slotID, stationID) VALUES (23, 8);
INSERT INTO slots (slotID, stationID) VALUES (24, 8);
INSERT INTO slots (slotID, stationID) VALUES (25, 8);
INSERT INTO slots (slotID, stationID) VALUES (26, 8);
INSERT INTO slots (slotID, stationID) VALUES (27, 8);
INSERT INTO slots (slotID, stationID) VALUES (28, 8);
INSERT INTO slots (slotID, stationID) VALUES (29, 8);
INSERT INTO slots (slotID, stationID) VALUES (30, 8);
INSERT INTO slots (slotID, stationID) VALUES (31, 8);
INSERT INTO slots (slotID, stationID) VALUES (32, 8);
INSERT INTO slots (slotID, stationID) VALUES (33, 8);
INSERT INTO slots (slotID, stationID) VALUES (34, 8);
INSERT INTO slots (slotID, stationID) VALUES (35, 8);
INSERT INTO slots (slotID, stationID) VALUES (36, 8);
INSERT INTO slots (slotID, stationID) VALUES (37, 8);
INSERT INTO slots (slotID, stationID) VALUES (38, 8);
INSERT INTO slots (slotID, stationID) VALUES (39, 8);
INSERT INTO slots (slotID, stationID) VALUES (40, 8);
INSERT INTO slots (slotID, stationID) VALUES (41, 8);
INSERT INTO slots (slotID, stationID) VALUES (42, 8);
INSERT INTO slots (slotID, stationID) VALUES (43, 8);
INSERT INTO slots (slotID, stationID) VALUES (44, 8);
INSERT INTO slots (slotID, stationID) VALUES (45, 8);
INSERT INTO slots (slotID, stationID) VALUES (46, 8);
INSERT INTO slots (slotID, stationID) VALUES (47, 8);
INSERT INTO slots (slotID, stationID) VALUES (48, 8);
INSERT INTO slots (slotID, stationID) VALUES (49, 8);
INSERT INTO slots (slotID, stationID) VALUES (50, 8);
INSERT INTO slots (slotID, stationID) VALUES (51, 8);
INSERT INTO slots (slotID, stationID) VALUES (52, 8);
INSERT INTO slots (slotID, stationID) VALUES (53, 8);
INSERT INTO slots (slotID, stationID) VALUES (54, 8);
INSERT INTO slots (slotID, stationID) VALUES (55, 8);
INSERT INTO slots (slotID, stationID) VALUES (56, 8);
INSERT INTO slots (slotID, stationID) VALUES (57, 8);
INSERT INTO slots (slotID, stationID) VALUES (58, 8);
INSERT INTO slots (slotID, stationID) VALUES (59, 8);
INSERT INTO slots (slotID, stationID) VALUES (60, 8);
INSERT INTO slots (slotID, stationID) VALUES (61, 8);
INSERT INTO slots (slotID, stationID) VALUES (62, 8);
INSERT INTO slots (slotID, stationID) VALUES (63, 8);
INSERT INTO slots (slotID, stationID) VALUES (64, 8);
INSERT INTO slots (slotID, stationID) VALUES (65, 8);
INSERT INTO slots (slotID, stationID) VALUES (66, 8);
INSERT INTO slots (slotID, stationID) VALUES (67, 8);
INSERT INTO slots (slotID, stationID) VALUES (68, 8);
INSERT INTO slots (slotID, stationID) VALUES (69, 8);
INSERT INTO slots (slotID, stationID) VALUES (70, 8);
INSERT INTO slots (slotID, stationID) VALUES (71, 8);
INSERT INTO slots (slotID, stationID) VALUES (72, 8);
INSERT INTO slots (slotID, stationID) VALUES (73, 8);
INSERT INTO slots (slotID, stationID) VALUES (74, 8);
INSERT INTO slots (slotID, stationID) VALUES (75, 8);
INSERT INTO slots (slotID, stationID) VALUES (76, 8);
INSERT INTO slots (slotID, stationID) VALUES (77, 8);
INSERT INTO slots (slotID, stationID) VALUES (78, 8);
INSERT INTO slots (slotID, stationID) VALUES (79, 8);
INSERT INTO slots (slotID, stationID) VALUES (80, 8);
INSERT INTO slots (slotID, stationID) VALUES (81, 8);
INSERT INTO slots (slotID, stationID) VALUES (82, 8);
INSERT INTO slots (slotID, stationID) VALUES (83, 8);
INSERT INTO slots (slotID, stationID) VALUES (84, 8);
INSERT INTO slots (slotID, stationID) VALUES (85, 8);
INSERT INTO slots (slotID, stationID) VALUES (86, 8);
INSERT INTO slots (slotID, stationID) VALUES (87, 8);
INSERT INTO slots (slotID, stationID) VALUES (88, 8);
INSERT INTO slots (slotID, stationID) VALUES (89, 8);
INSERT INTO slots (slotID, stationID) VALUES (90, 8);
INSERT INTO slots (slotID, stationID) VALUES (91, 8);
INSERT INTO slots (slotID, stationID) VALUES (92, 8);
INSERT INTO slots (slotID, stationID) VALUES (93, 8);
INSERT INTO slots (slotID, stationID) VALUES (94, 8);
INSERT INTO slots (slotID, stationID) VALUES (95, 8);
INSERT INTO slots (slotID, stationID) VALUES (96, 8);
INSERT INTO slots (slotID, stationID) VALUES (97, 8);
INSERT INTO slots (slotID, stationID) VALUES (98, 8);
INSERT INTO slots (slotID, stationID) VALUES (99, 8);
INSERT INTO slots (slotID, stationID) VALUES (100, 8);
INSERT INTO slots (slotID, stationID) VALUES (1, 9);
INSERT INTO slots (slotID, stationID) VALUES (2, 9);
INSERT INTO slots (slotID, stationID) VALUES (3, 9);
INSERT INTO slots (slotID, stationID) VALUES (4, 9);
INSERT INTO slots (slotID, stationID) VALUES (5, 9);
INSERT INTO slots (slotID, stationID) VALUES (6, 9);
INSERT INTO slots (slotID, stationID) VALUES (7, 9);
INSERT INTO slots (slotID, stationID) VALUES (8, 9);
INSERT INTO slots (slotID, stationID) VALUES (9, 9);
INSERT INTO slots (slotID, stationID) VALUES (10, 9);
INSERT INTO slots (slotID, stationID) VALUES (11, 9);
INSERT INTO slots (slotID, stationID) VALUES (12, 9);
INSERT INTO slots (slotID, stationID) VALUES (13, 9);
INSERT INTO slots (slotID, stationID) VALUES (14, 9);
INSERT INTO slots (slotID, stationID) VALUES (15, 9);
INSERT INTO slots (slotID, stationID) VALUES (16, 9);
INSERT INTO slots (slotID, stationID) VALUES (17, 9);
INSERT INTO slots (slotID, stationID) VALUES (18, 9);
INSERT INTO slots (slotID, stationID) VALUES (19, 9);
INSERT INTO slots (slotID, stationID) VALUES (20, 9);
INSERT INTO slots (slotID, stationID) VALUES (21, 9);
INSERT INTO slots (slotID, stationID) VALUES (22, 9);
INSERT INTO slots (slotID, stationID) VALUES (23, 9);
INSERT INTO slots (slotID, stationID) VALUES (24, 9);
INSERT INTO slots (slotID, stationID) VALUES (25, 9);
INSERT INTO slots (slotID, stationID) VALUES (26, 9);
INSERT INTO slots (slotID, stationID) VALUES (27, 9);
INSERT INTO slots (slotID, stationID) VALUES (28, 9);
INSERT INTO slots (slotID, stationID) VALUES (29, 9);
INSERT INTO slots (slotID, stationID) VALUES (30, 9);
INSERT INTO slots (slotID, stationID) VALUES (31, 9);
INSERT INTO slots (slotID, stationID) VALUES (32, 9);
INSERT INTO slots (slotID, stationID) VALUES (33, 9);
INSERT INTO slots (slotID, stationID) VALUES (34, 9);
INSERT INTO slots (slotID, stationID) VALUES (35, 9);
INSERT INTO slots (slotID, stationID) VALUES (36, 9);
INSERT INTO slots (slotID, stationID) VALUES (37, 9);
INSERT INTO slots (slotID, stationID) VALUES (38, 9);
INSERT INTO slots (slotID, stationID) VALUES (39, 9);
INSERT INTO slots (slotID, stationID) VALUES (40, 9);
INSERT INTO slots (slotID, stationID) VALUES (41, 9);
INSERT INTO slots (slotID, stationID) VALUES (42, 9);
INSERT INTO slots (slotID, stationID) VALUES (43, 9);
INSERT INTO slots (slotID, stationID) VALUES (44, 9);
INSERT INTO slots (slotID, stationID) VALUES (45, 9);
INSERT INTO slots (slotID, stationID) VALUES (46, 9);
INSERT INTO slots (slotID, stationID) VALUES (47, 9);
INSERT INTO slots (slotID, stationID) VALUES (48, 9);
INSERT INTO slots (slotID, stationID) VALUES (49, 9);
INSERT INTO slots (slotID, stationID) VALUES (50, 9);
INSERT INTO slots (slotID, stationID) VALUES (51, 9);
INSERT INTO slots (slotID, stationID) VALUES (52, 9);
INSERT INTO slots (slotID, stationID) VALUES (53, 9);
INSERT INTO slots (slotID, stationID) VALUES (54, 9);
INSERT INTO slots (slotID, stationID) VALUES (55, 9);
INSERT INTO slots (slotID, stationID) VALUES (56, 9);
INSERT INTO slots (slotID, stationID) VALUES (57, 9);
INSERT INTO slots (slotID, stationID) VALUES (58, 9);
INSERT INTO slots (slotID, stationID) VALUES (59, 9);
INSERT INTO slots (slotID, stationID) VALUES (60, 9);
INSERT INTO slots (slotID, stationID) VALUES (61, 9);
INSERT INTO slots (slotID, stationID) VALUES (62, 9);
INSERT INTO slots (slotID, stationID) VALUES (63, 9);
INSERT INTO slots (slotID, stationID) VALUES (64, 9);
INSERT INTO slots (slotID, stationID) VALUES (65, 9);
INSERT INTO slots (slotID, stationID) VALUES (66, 9);
INSERT INTO slots (slotID, stationID) VALUES (67, 9);
INSERT INTO slots (slotID, stationID) VALUES (68, 9);
INSERT INTO slots (slotID, stationID) VALUES (69, 9);
INSERT INTO slots (slotID, stationID) VALUES (70, 9);
INSERT INTO slots (slotID, stationID) VALUES (71, 9);
INSERT INTO slots (slotID, stationID) VALUES (72, 9);
INSERT INTO slots (slotID, stationID) VALUES (73, 9);
INSERT INTO slots (slotID, stationID) VALUES (74, 9);
INSERT INTO slots (slotID, stationID) VALUES (75, 9);
INSERT INTO slots (slotID, stationID) VALUES (76, 9);
INSERT INTO slots (slotID, stationID) VALUES (77, 9);
INSERT INTO slots (slotID, stationID) VALUES (78, 9);
INSERT INTO slots (slotID, stationID) VALUES (79, 9);
INSERT INTO slots (slotID, stationID) VALUES (80, 9);
INSERT INTO slots (slotID, stationID) VALUES (81, 9);
INSERT INTO slots (slotID, stationID) VALUES (82, 9);
INSERT INTO slots (slotID, stationID) VALUES (83, 9);
INSERT INTO slots (slotID, stationID) VALUES (84, 9);
INSERT INTO slots (slotID, stationID) VALUES (85, 9);
INSERT INTO slots (slotID, stationID) VALUES (86, 9);
INSERT INTO slots (slotID, stationID) VALUES (87, 9);
INSERT INTO slots (slotID, stationID) VALUES (88, 9);
INSERT INTO slots (slotID, stationID) VALUES (89, 9);
INSERT INTO slots (slotID, stationID) VALUES (90, 9);
INSERT INTO slots (slotID, stationID) VALUES (91, 9);
INSERT INTO slots (slotID, stationID) VALUES (92, 9);
INSERT INTO slots (slotID, stationID) VALUES (93, 9);
INSERT INTO slots (slotID, stationID) VALUES (94, 9);
INSERT INTO slots (slotID, stationID) VALUES (95, 9);
INSERT INTO slots (slotID, stationID) VALUES (96, 9);
INSERT INTO slots (slotID, stationID) VALUES (97, 9);
INSERT INTO slots (slotID, stationID) VALUES (98, 9);
INSERT INTO slots (slotID, stationID) VALUES (99, 9);
INSERT INTO slots (slotID, stationID) VALUES (100, 9);
INSERT INTO slots (slotID, stationID) VALUES (1, 10);
INSERT INTO slots (slotID, stationID) VALUES (2, 10);
INSERT INTO slots (slotID, stationID) VALUES (3, 10);
INSERT INTO slots (slotID, stationID) VALUES (4, 10);
INSERT INTO slots (slotID, stationID) VALUES (5, 10);
INSERT INTO slots (slotID, stationID) VALUES (6, 10);
INSERT INTO slots (slotID, stationID) VALUES (7, 10);
INSERT INTO slots (slotID, stationID) VALUES (8, 10);
INSERT INTO slots (slotID, stationID) VALUES (9, 10);
INSERT INTO slots (slotID, stationID) VALUES (10, 10);
INSERT INTO slots (slotID, stationID) VALUES (11, 10);
INSERT INTO slots (slotID, stationID) VALUES (12, 10);
INSERT INTO slots (slotID, stationID) VALUES (13, 10);
INSERT INTO slots (slotID, stationID) VALUES (14, 10);
INSERT INTO slots (slotID, stationID) VALUES (15, 10);
INSERT INTO slots (slotID, stationID) VALUES (16, 10);
INSERT INTO slots (slotID, stationID) VALUES (17, 10);
INSERT INTO slots (slotID, stationID) VALUES (18, 10);
INSERT INTO slots (slotID, stationID) VALUES (19, 10);
INSERT INTO slots (slotID, stationID) VALUES (20, 10);
INSERT INTO slots (slotID, stationID) VALUES (21, 10);
INSERT INTO slots (slotID, stationID) VALUES (22, 10);
INSERT INTO slots (slotID, stationID) VALUES (23, 10);
INSERT INTO slots (slotID, stationID) VALUES (24, 10);
INSERT INTO slots (slotID, stationID) VALUES (25, 10);
INSERT INTO slots (slotID, stationID) VALUES (26, 10);
INSERT INTO slots (slotID, stationID) VALUES (27, 10);
INSERT INTO slots (slotID, stationID) VALUES (28, 10);
INSERT INTO slots (slotID, stationID) VALUES (29, 10);
INSERT INTO slots (slotID, stationID) VALUES (30, 10);
INSERT INTO slots (slotID, stationID) VALUES (31, 10);
INSERT INTO slots (slotID, stationID) VALUES (32, 10);
INSERT INTO slots (slotID, stationID) VALUES (33, 10);
INSERT INTO slots (slotID, stationID) VALUES (34, 10);
INSERT INTO slots (slotID, stationID) VALUES (35, 10);
INSERT INTO slots (slotID, stationID) VALUES (36, 10);
INSERT INTO slots (slotID, stationID) VALUES (37, 10);
INSERT INTO slots (slotID, stationID) VALUES (38, 10);
INSERT INTO slots (slotID, stationID) VALUES (39, 10);
INSERT INTO slots (slotID, stationID) VALUES (40, 10);
INSERT INTO slots (slotID, stationID) VALUES (41, 10);
INSERT INTO slots (slotID, stationID) VALUES (42, 10);
INSERT INTO slots (slotID, stationID) VALUES (43, 10);
INSERT INTO slots (slotID, stationID) VALUES (44, 10);
INSERT INTO slots (slotID, stationID) VALUES (45, 10);
INSERT INTO slots (slotID, stationID) VALUES (46, 10);
INSERT INTO slots (slotID, stationID) VALUES (47, 10);
INSERT INTO slots (slotID, stationID) VALUES (48, 10);
INSERT INTO slots (slotID, stationID) VALUES (49, 10);
INSERT INTO slots (slotID, stationID) VALUES (50, 10);
INSERT INTO slots (slotID, stationID) VALUES (51, 10);
INSERT INTO slots (slotID, stationID) VALUES (52, 10);
INSERT INTO slots (slotID, stationID) VALUES (53, 10);
INSERT INTO slots (slotID, stationID) VALUES (54, 10);
INSERT INTO slots (slotID, stationID) VALUES (55, 10);
INSERT INTO slots (slotID, stationID) VALUES (56, 10);
INSERT INTO slots (slotID, stationID) VALUES (57, 10);
INSERT INTO slots (slotID, stationID) VALUES (58, 10);
INSERT INTO slots (slotID, stationID) VALUES (59, 10);
INSERT INTO slots (slotID, stationID) VALUES (60, 10);
INSERT INTO slots (slotID, stationID) VALUES (61, 10);
INSERT INTO slots (slotID, stationID) VALUES (62, 10);
INSERT INTO slots (slotID, stationID) VALUES (63, 10);
INSERT INTO slots (slotID, stationID) VALUES (64, 10);
INSERT INTO slots (slotID, stationID) VALUES (65, 10);
INSERT INTO slots (slotID, stationID) VALUES (66, 10);
INSERT INTO slots (slotID, stationID) VALUES (67, 10);
INSERT INTO slots (slotID, stationID) VALUES (68, 10);
INSERT INTO slots (slotID, stationID) VALUES (69, 10);
INSERT INTO slots (slotID, stationID) VALUES (70, 10);
INSERT INTO slots (slotID, stationID) VALUES (71, 10);
INSERT INTO slots (slotID, stationID) VALUES (72, 10);
INSERT INTO slots (slotID, stationID) VALUES (73, 10);
INSERT INTO slots (slotID, stationID) VALUES (74, 10);
INSERT INTO slots (slotID, stationID) VALUES (75, 10);
INSERT INTO slots (slotID, stationID) VALUES (76, 10);
INSERT INTO slots (slotID, stationID) VALUES (77, 10);
INSERT INTO slots (slotID, stationID) VALUES (78, 10);
INSERT INTO slots (slotID, stationID) VALUES (79, 10);
INSERT INTO slots (slotID, stationID) VALUES (80, 10);
INSERT INTO slots (slotID, stationID) VALUES (81, 10);
INSERT INTO slots (slotID, stationID) VALUES (82, 10);
INSERT INTO slots (slotID, stationID) VALUES (83, 10);
INSERT INTO slots (slotID, stationID) VALUES (84, 10);
INSERT INTO slots (slotID, stationID) VALUES (85, 10);
INSERT INTO slots (slotID, stationID) VALUES (86, 10);
INSERT INTO slots (slotID, stationID) VALUES (87, 10);
INSERT INTO slots (slotID, stationID) VALUES (88, 10);
INSERT INTO slots (slotID, stationID) VALUES (89, 10);
INSERT INTO slots (slotID, stationID) VALUES (90, 10);
INSERT INTO slots (slotID, stationID) VALUES (91, 10);
INSERT INTO slots (slotID, stationID) VALUES (92, 10);
INSERT INTO slots (slotID, stationID) VALUES (93, 10);
INSERT INTO slots (slotID, stationID) VALUES (94, 10);
INSERT INTO slots (slotID, stationID) VALUES (95, 10);
INSERT INTO slots (slotID, stationID) VALUES (96, 10);
INSERT INTO slots (slotID, stationID) VALUES (97, 10);
INSERT INTO slots (slotID, stationID) VALUES (98, 10);
INSERT INTO slots (slotID, stationID) VALUES (99, 10);
INSERT INTO slots (slotID, stationID) VALUES (100, 10);

INSERT INTO user_types (description) VALUES ("Administrator");
INSERT INTO user_types (description) VALUES ("Reperatør");
INSERT INTO user_types (description) VALUES ("Kunde");

UPDATE slots SET bikeID = 1 WHERE slotID = 1 AND stationID = 1;
UPDATE slots SET bikeID = 2 WHERE slotID = 2 AND stationID = 1;
UPDATE slots SET bikeID = 3 WHERE slotID = 3 AND stationID = 1;
UPDATE slots SET bikeID = 4 WHERE slotID = 4 AND stationID = 1;
UPDATE slots SET bikeID = 5 WHERE slotID = 5 AND stationID = 1;
UPDATE slots SET bikeID = 6 WHERE slotID = 6 AND stationID = 1;
UPDATE slots SET bikeID = 7 WHERE slotID = 7 AND stationID = 1;
UPDATE slots SET bikeID = 8 WHERE slotID = 8 AND stationID = 1;
UPDATE slots SET bikeID = 9 WHERE slotID = 9 AND stationID = 1;
UPDATE slots SET bikeID = 10 WHERE slotID = 10 AND stationID = 1;
UPDATE slots SET bikeID = 11 WHERE slotID = 11 AND stationID = 1;
UPDATE slots SET bikeID = 12 WHERE slotID = 12 AND stationID = 1;
UPDATE slots SET bikeID = 13 WHERE slotID = 13 AND stationID = 1;
UPDATE slots SET bikeID = 14 WHERE slotID = 14 AND stationID = 1;
UPDATE slots SET bikeID = 15 WHERE slotID = 15 AND stationID = 1;
UPDATE slots SET bikeID = 16 WHERE slotID = 16 AND stationID = 1;
UPDATE slots SET bikeID = 17 WHERE slotID = 17 AND stationID = 1;
UPDATE slots SET bikeID = 18 WHERE slotID = 18 AND stationID = 1;
UPDATE slots SET bikeID = 19 WHERE slotID = 19 AND stationID = 1;
UPDATE slots SET bikeID = 20 WHERE slotID = 20 AND stationID = 1;
UPDATE slots SET bikeID = 21 WHERE slotID = 21 AND stationID = 1;
UPDATE slots SET bikeID = 22 WHERE slotID = 22 AND stationID = 1;
UPDATE slots SET bikeID = 23 WHERE slotID = 23 AND stationID = 1;
UPDATE slots SET bikeID = 24 WHERE slotID = 24 AND stationID = 1;
UPDATE slots SET bikeID = 25 WHERE slotID = 25 AND stationID = 1;
UPDATE slots SET bikeID = 26 WHERE slotID = 26 AND stationID = 1;
UPDATE slots SET bikeID = 27 WHERE slotID = 27 AND stationID = 1;
UPDATE slots SET bikeID = 28 WHERE slotID = 28 AND stationID = 1;
UPDATE slots SET bikeID = 29 WHERE slotID = 29 AND stationID = 1;
UPDATE slots SET bikeID = 30 WHERE slotID = 30 AND stationID = 1;
UPDATE slots SET bikeID = 31 WHERE slotID = 31 AND stationID = 1;
UPDATE slots SET bikeID = 32 WHERE slotID = 32 AND stationID = 1;
UPDATE slots SET bikeID = 33 WHERE slotID = 33 AND stationID = 1;
UPDATE slots SET bikeID = 34 WHERE slotID = 34 AND stationID = 1;
UPDATE slots SET bikeID = 35 WHERE slotID = 35 AND stationID = 1;
UPDATE slots SET bikeID = 36 WHERE slotID = 36 AND stationID = 1;
UPDATE slots SET bikeID = 37 WHERE slotID = 37 AND stationID = 1;
UPDATE slots SET bikeID = 38 WHERE slotID = 38 AND stationID = 1;
UPDATE slots SET bikeID = 39 WHERE slotID = 39 AND stationID = 1;
UPDATE slots SET bikeID = 40 WHERE slotID = 40 AND stationID = 1;
UPDATE slots SET bikeID = 41 WHERE slotID = 41 AND stationID = 1;
UPDATE slots SET bikeID = 42 WHERE slotID = 42 AND stationID = 1;
UPDATE slots SET bikeID = 43 WHERE slotID = 43 AND stationID = 1;
UPDATE slots SET bikeID = 44 WHERE slotID = 44 AND stationID = 1;
UPDATE slots SET bikeID = 45 WHERE slotID = 45 AND stationID = 1;
UPDATE slots SET bikeID = 46 WHERE slotID = 46 AND stationID = 1;
UPDATE slots SET bikeID = 47 WHERE slotID = 47 AND stationID = 1;
UPDATE slots SET bikeID = 48 WHERE slotID = 48 AND stationID = 1;
UPDATE slots SET bikeID = 49 WHERE slotID = 49 AND stationID = 1;
UPDATE slots SET bikeID = 50 WHERE slotID = 50 AND stationID = 1;
UPDATE slots SET bikeID = 51 WHERE slotID = 1 AND stationID = 2;
UPDATE slots SET bikeID = 52 WHERE slotID = 2 AND stationID = 2;
UPDATE slots SET bikeID = 53 WHERE slotID = 3 AND stationID = 2;
UPDATE slots SET bikeID = 54 WHERE slotID = 4 AND stationID = 2;
UPDATE slots SET bikeID = 55 WHERE slotID = 5 AND stationID = 2;
UPDATE slots SET bikeID = 56 WHERE slotID = 6 AND stationID = 2;
UPDATE slots SET bikeID = 57 WHERE slotID = 7 AND stationID = 2;
UPDATE slots SET bikeID = 58 WHERE slotID = 8 AND stationID = 2;
UPDATE slots SET bikeID = 59 WHERE slotID = 9 AND stationID = 2;
UPDATE slots SET bikeID = 60 WHERE slotID = 10 AND stationID = 2;
UPDATE slots SET bikeID = 61 WHERE slotID = 11 AND stationID = 2;
UPDATE slots SET bikeID = 62 WHERE slotID = 12 AND stationID = 2;
UPDATE slots SET bikeID = 63 WHERE slotID = 13 AND stationID = 2;
UPDATE slots SET bikeID = 64 WHERE slotID = 14 AND stationID = 2;
UPDATE slots SET bikeID = 65 WHERE slotID = 15 AND stationID = 2;
UPDATE slots SET bikeID = 66 WHERE slotID = 16 AND stationID = 2;
UPDATE slots SET bikeID = 67 WHERE slotID = 17 AND stationID = 2;
UPDATE slots SET bikeID = 68 WHERE slotID = 18 AND stationID = 2;
UPDATE slots SET bikeID = 69 WHERE slotID = 19 AND stationID = 2;
UPDATE slots SET bikeID = 70 WHERE slotID = 20 AND stationID = 2;
UPDATE slots SET bikeID = 71 WHERE slotID = 21 AND stationID = 2;
UPDATE slots SET bikeID = 72 WHERE slotID = 22 AND stationID = 2;
UPDATE slots SET bikeID = 73 WHERE slotID = 23 AND stationID = 2;
UPDATE slots SET bikeID = 74 WHERE slotID = 24 AND stationID = 2;
UPDATE slots SET bikeID = 75 WHERE slotID = 25 AND stationID = 2;
UPDATE slots SET bikeID = 76 WHERE slotID = 26 AND stationID = 2;
UPDATE slots SET bikeID = 77 WHERE slotID = 27 AND stationID = 2;
UPDATE slots SET bikeID = 78 WHERE slotID = 28 AND stationID = 2;
UPDATE slots SET bikeID = 79 WHERE slotID = 29 AND stationID = 2;
UPDATE slots SET bikeID = 80 WHERE slotID = 30 AND stationID = 2;
UPDATE slots SET bikeID = 81 WHERE slotID = 31 AND stationID = 2;
UPDATE slots SET bikeID = 82 WHERE slotID = 32 AND stationID = 2;
UPDATE slots SET bikeID = 83 WHERE slotID = 33 AND stationID = 2;
UPDATE slots SET bikeID = 84 WHERE slotID = 34 AND stationID = 2;
UPDATE slots SET bikeID = 85 WHERE slotID = 35 AND stationID = 2;
UPDATE slots SET bikeID = 86 WHERE slotID = 36 AND stationID = 2;
UPDATE slots SET bikeID = 87 WHERE slotID = 37 AND stationID = 2;
UPDATE slots SET bikeID = 88 WHERE slotID = 38 AND stationID = 2;
UPDATE slots SET bikeID = 89 WHERE slotID = 39 AND stationID = 2;
UPDATE slots SET bikeID = 90 WHERE slotID = 40 AND stationID = 2;
UPDATE slots SET bikeID = 91 WHERE slotID = 41 AND stationID = 2;
UPDATE slots SET bikeID = 92 WHERE slotID = 42 AND stationID = 2;
UPDATE slots SET bikeID = 93 WHERE slotID = 43 AND stationID = 2;
UPDATE slots SET bikeID = 94 WHERE slotID = 44 AND stationID = 2;
UPDATE slots SET bikeID = 95 WHERE slotID = 45 AND stationID = 2;
UPDATE slots SET bikeID = 96 WHERE slotID = 46 AND stationID = 2;
UPDATE slots SET bikeID = 97 WHERE slotID = 47 AND stationID = 2;
UPDATE slots SET bikeID = 98 WHERE slotID = 48 AND stationID = 2;
UPDATE slots SET bikeID = 99 WHERE slotID = 49 AND stationID = 2;
UPDATE slots SET bikeID = 100 WHERE slotID = 50 AND stationID = 2;
UPDATE slots SET bikeID = 101 WHERE slotID = 1 AND stationID = 3;
UPDATE slots SET bikeID = 102 WHERE slotID = 2 AND stationID = 3;
UPDATE slots SET bikeID = 103 WHERE slotID = 3 AND stationID = 3;
UPDATE slots SET bikeID = 104 WHERE slotID = 4 AND stationID = 3;
UPDATE slots SET bikeID = 105 WHERE slotID = 5 AND stationID = 3;
UPDATE slots SET bikeID = 106 WHERE slotID = 6 AND stationID = 3;
UPDATE slots SET bikeID = 107 WHERE slotID = 7 AND stationID = 3;
UPDATE slots SET bikeID = 108 WHERE slotID = 8 AND stationID = 3;
UPDATE slots SET bikeID = 109 WHERE slotID = 9 AND stationID = 3;
UPDATE slots SET bikeID = 110 WHERE slotID = 10 AND stationID = 3;
UPDATE slots SET bikeID = 111 WHERE slotID = 11 AND stationID = 3;
UPDATE slots SET bikeID = 112 WHERE slotID = 12 AND stationID = 3;
UPDATE slots SET bikeID = 113 WHERE slotID = 13 AND stationID = 3;
UPDATE slots SET bikeID = 114 WHERE slotID = 14 AND stationID = 3;
UPDATE slots SET bikeID = 115 WHERE slotID = 15 AND stationID = 3;
UPDATE slots SET bikeID = 116 WHERE slotID = 16 AND stationID = 3;
UPDATE slots SET bikeID = 117 WHERE slotID = 17 AND stationID = 3;
UPDATE slots SET bikeID = 118 WHERE slotID = 18 AND stationID = 3;
UPDATE slots SET bikeID = 119 WHERE slotID = 19 AND stationID = 3;
UPDATE slots SET bikeID = 120 WHERE slotID = 20 AND stationID = 3;
UPDATE slots SET bikeID = 121 WHERE slotID = 21 AND stationID = 3;
UPDATE slots SET bikeID = 122 WHERE slotID = 22 AND stationID = 3;
UPDATE slots SET bikeID = 123 WHERE slotID = 23 AND stationID = 3;
UPDATE slots SET bikeID = 124 WHERE slotID = 24 AND stationID = 3;
UPDATE slots SET bikeID = 125 WHERE slotID = 25 AND stationID = 3;
UPDATE slots SET bikeID = 126 WHERE slotID = 26 AND stationID = 3;
UPDATE slots SET bikeID = 127 WHERE slotID = 27 AND stationID = 3;
UPDATE slots SET bikeID = 128 WHERE slotID = 28 AND stationID = 3;
UPDATE slots SET bikeID = 129 WHERE slotID = 29 AND stationID = 3;
UPDATE slots SET bikeID = 130 WHERE slotID = 30 AND stationID = 3;
UPDATE slots SET bikeID = 131 WHERE slotID = 31 AND stationID = 3;
UPDATE slots SET bikeID = 132 WHERE slotID = 32 AND stationID = 3;
UPDATE slots SET bikeID = 133 WHERE slotID = 33 AND stationID = 3;
UPDATE slots SET bikeID = 134 WHERE slotID = 34 AND stationID = 3;
UPDATE slots SET bikeID = 135 WHERE slotID = 35 AND stationID = 3;
UPDATE slots SET bikeID = 136 WHERE slotID = 36 AND stationID = 3;
UPDATE slots SET bikeID = 137 WHERE slotID = 37 AND stationID = 3;
UPDATE slots SET bikeID = 138 WHERE slotID = 38 AND stationID = 3;
UPDATE slots SET bikeID = 139 WHERE slotID = 39 AND stationID = 3;
UPDATE slots SET bikeID = 140 WHERE slotID = 40 AND stationID = 3;
UPDATE slots SET bikeID = 141 WHERE slotID = 41 AND stationID = 3;
UPDATE slots SET bikeID = 142 WHERE slotID = 42 AND stationID = 3;
UPDATE slots SET bikeID = 143 WHERE slotID = 43 AND stationID = 3;
UPDATE slots SET bikeID = 144 WHERE slotID = 44 AND stationID = 3;
UPDATE slots SET bikeID = 145 WHERE slotID = 45 AND stationID = 3;
UPDATE slots SET bikeID = 146 WHERE slotID = 46 AND stationID = 3;
UPDATE slots SET bikeID = 147 WHERE slotID = 47 AND stationID = 3;
UPDATE slots SET bikeID = 148 WHERE slotID = 48 AND stationID = 3;
UPDATE slots SET bikeID = 149 WHERE slotID = 49 AND stationID = 3;
UPDATE slots SET bikeID = 150 WHERE slotID = 50 AND stationID = 3;
UPDATE slots SET bikeID = 151 WHERE slotID = 1 AND stationID = 4;
UPDATE slots SET bikeID = 152 WHERE slotID = 2 AND stationID = 4;
UPDATE slots SET bikeID = 153 WHERE slotID = 3 AND stationID = 4;
UPDATE slots SET bikeID = 154 WHERE slotID = 4 AND stationID = 4;
UPDATE slots SET bikeID = 155 WHERE slotID = 5 AND stationID = 4;
UPDATE slots SET bikeID = 156 WHERE slotID = 6 AND stationID = 4;
UPDATE slots SET bikeID = 157 WHERE slotID = 7 AND stationID = 4;
UPDATE slots SET bikeID = 158 WHERE slotID = 8 AND stationID = 4;
UPDATE slots SET bikeID = 159 WHERE slotID = 9 AND stationID = 4;
UPDATE slots SET bikeID = 160 WHERE slotID = 10 AND stationID = 4;
UPDATE slots SET bikeID = 161 WHERE slotID = 11 AND stationID = 4;
UPDATE slots SET bikeID = 162 WHERE slotID = 12 AND stationID = 4;
UPDATE slots SET bikeID = 163 WHERE slotID = 13 AND stationID = 4;
UPDATE slots SET bikeID = 164 WHERE slotID = 14 AND stationID = 4;
UPDATE slots SET bikeID = 165 WHERE slotID = 15 AND stationID = 4;
UPDATE slots SET bikeID = 166 WHERE slotID = 16 AND stationID = 4;
UPDATE slots SET bikeID = 167 WHERE slotID = 17 AND stationID = 4;
UPDATE slots SET bikeID = 168 WHERE slotID = 18 AND stationID = 4;
UPDATE slots SET bikeID = 169 WHERE slotID = 19 AND stationID = 4;
UPDATE slots SET bikeID = 170 WHERE slotID = 20 AND stationID = 4;
UPDATE slots SET bikeID = 171 WHERE slotID = 21 AND stationID = 4;
UPDATE slots SET bikeID = 172 WHERE slotID = 22 AND stationID = 4;
UPDATE slots SET bikeID = 173 WHERE slotID = 23 AND stationID = 4;
UPDATE slots SET bikeID = 174 WHERE slotID = 24 AND stationID = 4;
UPDATE slots SET bikeID = 175 WHERE slotID = 25 AND stationID = 4;
UPDATE slots SET bikeID = 176 WHERE slotID = 26 AND stationID = 4;
UPDATE slots SET bikeID = 177 WHERE slotID = 27 AND stationID = 4;
UPDATE slots SET bikeID = 178 WHERE slotID = 28 AND stationID = 4;
UPDATE slots SET bikeID = 179 WHERE slotID = 29 AND stationID = 4;
UPDATE slots SET bikeID = 180 WHERE slotID = 30 AND stationID = 4;
UPDATE slots SET bikeID = 181 WHERE slotID = 31 AND stationID = 4;
UPDATE slots SET bikeID = 182 WHERE slotID = 32 AND stationID = 4;
UPDATE slots SET bikeID = 183 WHERE slotID = 33 AND stationID = 4;
UPDATE slots SET bikeID = 184 WHERE slotID = 34 AND stationID = 4;
UPDATE slots SET bikeID = 185 WHERE slotID = 35 AND stationID = 4;
UPDATE slots SET bikeID = 186 WHERE slotID = 36 AND stationID = 4;
UPDATE slots SET bikeID = 187 WHERE slotID = 37 AND stationID = 4;
UPDATE slots SET bikeID = 188 WHERE slotID = 38 AND stationID = 4;
UPDATE slots SET bikeID = 189 WHERE slotID = 39 AND stationID = 4;
UPDATE slots SET bikeID = 190 WHERE slotID = 40 AND stationID = 4;
UPDATE slots SET bikeID = 191 WHERE slotID = 41 AND stationID = 4;
UPDATE slots SET bikeID = 192 WHERE slotID = 42 AND stationID = 4;
UPDATE slots SET bikeID = 193 WHERE slotID = 43 AND stationID = 4;
UPDATE slots SET bikeID = 194 WHERE slotID = 44 AND stationID = 4;
UPDATE slots SET bikeID = 195 WHERE slotID = 45 AND stationID = 4;
UPDATE slots SET bikeID = 196 WHERE slotID = 46 AND stationID = 4;
UPDATE slots SET bikeID = 197 WHERE slotID = 47 AND stationID = 4;
UPDATE slots SET bikeID = 198 WHERE slotID = 48 AND stationID = 4;
UPDATE slots SET bikeID = 199 WHERE slotID = 49 AND stationID = 4;
UPDATE slots SET bikeID = 200 WHERE slotID = 50 AND stationID = 4;
UPDATE slots SET bikeID = 201 WHERE slotID = 1 AND stationID = 5;
UPDATE slots SET bikeID = 202 WHERE slotID = 2 AND stationID = 5;
UPDATE slots SET bikeID = 203 WHERE slotID = 3 AND stationID = 5;
UPDATE slots SET bikeID = 204 WHERE slotID = 4 AND stationID = 5;
UPDATE slots SET bikeID = 205 WHERE slotID = 5 AND stationID = 5;
UPDATE slots SET bikeID = 206 WHERE slotID = 6 AND stationID = 5;
UPDATE slots SET bikeID = 207 WHERE slotID = 7 AND stationID = 5;
UPDATE slots SET bikeID = 208 WHERE slotID = 8 AND stationID = 5;
UPDATE slots SET bikeID = 209 WHERE slotID = 9 AND stationID = 5;
UPDATE slots SET bikeID = 210 WHERE slotID = 10 AND stationID = 5;
UPDATE slots SET bikeID = 211 WHERE slotID = 11 AND stationID = 5;
UPDATE slots SET bikeID = 212 WHERE slotID = 12 AND stationID = 5;
UPDATE slots SET bikeID = 213 WHERE slotID = 13 AND stationID = 5;
UPDATE slots SET bikeID = 214 WHERE slotID = 14 AND stationID = 5;
UPDATE slots SET bikeID = 215 WHERE slotID = 15 AND stationID = 5;
UPDATE slots SET bikeID = 216 WHERE slotID = 16 AND stationID = 5;
UPDATE slots SET bikeID = 217 WHERE slotID = 17 AND stationID = 5;
UPDATE slots SET bikeID = 218 WHERE slotID = 18 AND stationID = 5;
UPDATE slots SET bikeID = 219 WHERE slotID = 19 AND stationID = 5;
UPDATE slots SET bikeID = 220 WHERE slotID = 20 AND stationID = 5;
UPDATE slots SET bikeID = 221 WHERE slotID = 21 AND stationID = 5;
UPDATE slots SET bikeID = 222 WHERE slotID = 22 AND stationID = 5;
UPDATE slots SET bikeID = 223 WHERE slotID = 23 AND stationID = 5;
UPDATE slots SET bikeID = 224 WHERE slotID = 24 AND stationID = 5;
UPDATE slots SET bikeID = 225 WHERE slotID = 25 AND stationID = 5;
UPDATE slots SET bikeID = 226 WHERE slotID = 26 AND stationID = 5;
UPDATE slots SET bikeID = 227 WHERE slotID = 27 AND stationID = 5;
UPDATE slots SET bikeID = 228 WHERE slotID = 28 AND stationID = 5;
UPDATE slots SET bikeID = 229 WHERE slotID = 29 AND stationID = 5;
UPDATE slots SET bikeID = 230 WHERE slotID = 30 AND stationID = 5;
UPDATE slots SET bikeID = 231 WHERE slotID = 31 AND stationID = 5;
UPDATE slots SET bikeID = 232 WHERE slotID = 32 AND stationID = 5;
UPDATE slots SET bikeID = 233 WHERE slotID = 33 AND stationID = 5;
UPDATE slots SET bikeID = 234 WHERE slotID = 34 AND stationID = 5;
UPDATE slots SET bikeID = 235 WHERE slotID = 35 AND stationID = 5;
UPDATE slots SET bikeID = 236 WHERE slotID = 36 AND stationID = 5;
UPDATE slots SET bikeID = 237 WHERE slotID = 37 AND stationID = 5;
UPDATE slots SET bikeID = 238 WHERE slotID = 38 AND stationID = 5;
UPDATE slots SET bikeID = 239 WHERE slotID = 39 AND stationID = 5;
UPDATE slots SET bikeID = 240 WHERE slotID = 40 AND stationID = 5;
UPDATE slots SET bikeID = 241 WHERE slotID = 41 AND stationID = 5;
UPDATE slots SET bikeID = 242 WHERE slotID = 42 AND stationID = 5;
UPDATE slots SET bikeID = 243 WHERE slotID = 43 AND stationID = 5;
UPDATE slots SET bikeID = 244 WHERE slotID = 44 AND stationID = 5;
UPDATE slots SET bikeID = 245 WHERE slotID = 45 AND stationID = 5;
UPDATE slots SET bikeID = 246 WHERE slotID = 46 AND stationID = 5;
UPDATE slots SET bikeID = 247 WHERE slotID = 47 AND stationID = 5;
UPDATE slots SET bikeID = 248 WHERE slotID = 48 AND stationID = 5;
UPDATE slots SET bikeID = 249 WHERE slotID = 49 AND stationID = 5;
UPDATE slots SET bikeID = 250 WHERE slotID = 50 AND stationID = 5;

INSERT INTO users (userTypeID, email, password, salt, firstname, lastname, phone, landcode) VALUES (3, 'martin@mail.com', 'passord', 'salt', 'Martin', 'Moan', 99999999, 0047);
INSERT INTO users (userTypeID, email, password, salt, firstname, lastname, phone, landcode) VALUES (3, 'frank@mail.com', 'passord', 'salt', 'Frank', 'Kjosås', 66666666, 0047);
INSERT INTO users (userTypeID, email, password, salt, firstname, lastname, phone, landcode) VALUES (3, 'jonnyboi@mail.com', 'passord', 'salt', 'Jonas Gahr', 'Støre', 70707070, 0047);
