/*
	For this script to work, the script DBSetup.sql must be run first,
	so that any auto incremented id numbers are regenerated.
	But this will delete any content previously registered in the database
*/

INSERT INTO bikes (price, make, type) VALUES (3682, "Merida", "Bysykkel");
INSERT INTO bikes (price, make, type) VALUES (666, "DBS", "Bysykkel");
INSERT INTO bikes (price, make, type) VALUES (3883, "Scott", "Landevei");
INSERT INTO bikes (price, make, type) VALUES (774, "DBS", "Bysykkel");
INSERT INTO bikes (price, make, type) VALUES (1118, "Trek", "Terreng");
INSERT INTO bikes (price, make, type) VALUES (2068, "Trek", "Hybrid");
INSERT INTO bikes (price, make, type) VALUES (764, "Trek", "Bysykkel");
INSERT INTO bikes (price, make, type) VALUES (3442, "Scott", "Landevei");
INSERT INTO bikes (price, make, type) VALUES (4355, "DBS", "Landevei");
INSERT INTO bikes (price, make, type) VALUES (1599, "DBS", "Terreng");
INSERT INTO bikes (price, make, type) VALUES (4631, "Trek", "Landevei");
INSERT INTO bikes (price, make, type) VALUES (3033, "Scott", "Bysykkel");
INSERT INTO bikes (price, make, type) VALUES (1757, "DBS", "Hybrid");
INSERT INTO bikes (price, make, type) VALUES (2098, "Trek", "Bysykkel");
INSERT INTO bikes (price, make, type) VALUES (4271, "Trek", "Hybrid");
INSERT INTO bikes (price, make, type) VALUES (1155, "Scott", "Hybrid");
INSERT INTO bikes (price, make, type) VALUES (4065, "DBS", "Landevei");
INSERT INTO bikes (price, make, type) VALUES (2768, "DBS", "Hybrid");
INSERT INTO bikes (price, make, type) VALUES (4722, "Merida", "Bysykkel");
INSERT INTO bikes (price, make, type) VALUES (4106, "DBS", "Landevei");
INSERT INTO bikes (price, make, type) VALUES (1161, "DBS", "Hybrid");
INSERT INTO bikes (price, make, type) VALUES (2362, "Trek", "Hybrid");
INSERT INTO bikes (price, make, type) VALUES (2457, "Trek", "Terreng");
INSERT INTO bikes (price, make, type) VALUES (2087, "Scott", "Bysykkel");
INSERT INTO bikes (price, make, type) VALUES (3442, "Merida", "Terreng");
INSERT INTO bikes (price, make, type) VALUES (3923, "DBS", "Landevei");
INSERT INTO bikes (price, make, type) VALUES (2074, "DBS", "Landevei");
INSERT INTO bikes (price, make, type) VALUES (1692, "DBS", "Terreng");
INSERT INTO bikes (price, make, type) VALUES (1633, "Merida", "Landevei");
INSERT INTO bikes (price, make, type) VALUES (4868, "DBS", "Terreng");
INSERT INTO bikes (price, make, type) VALUES (1336, "Merida", "Hybrid");
INSERT INTO bikes (price, make, type) VALUES (3747, "Merida", "Hybrid");
INSERT INTO bikes (price, make, type) VALUES (4857, "DBS", "Landevei");
INSERT INTO bikes (price, make, type) VALUES (3217, "Trek", "Terreng");
INSERT INTO bikes (price, make, type) VALUES (3362, "Scott", "Terreng");
INSERT INTO bikes (price, make, type) VALUES (1349, "Merida", "Bysykkel");
INSERT INTO bikes (price, make, type) VALUES (3927, "DBS", "Bysykkel");
INSERT INTO bikes (price, make, type) VALUES (3779, "Merida", "Hybrid");
INSERT INTO bikes (price, make, type) VALUES (4746, "Trek", "Bysykkel");
INSERT INTO bikes (price, make, type) VALUES (976, "Scott", "Landevei");
INSERT INTO bikes (price, make, type) VALUES (4096, "Merida", "Hybrid");
INSERT INTO bikes (price, make, type) VALUES (688, "Scott", "Landevei");
INSERT INTO bikes (price, make, type) VALUES (1109, "Merida", "Hybrid");
INSERT INTO bikes (price, make, type) VALUES (4434, "DBS", "Landevei");
INSERT INTO bikes (price, make, type) VALUES (3640, "DBS", "Hybrid");
INSERT INTO bikes (price, make, type) VALUES (3653, "Merida", "Terreng");
INSERT INTO bikes (price, make, type) VALUES (2317, "Trek", "Hybrid");
INSERT INTO bikes (price, make, type) VALUES (2966, "Trek", "Bysykkel");
INSERT INTO bikes (price, make, type) VALUES (4418, "Merida", "Terreng");
INSERT INTO bikes (price, make, type) VALUES (601, "Trek", "Bysykkel");
INSERT INTO bikes (price, make, type) VALUES (822, "Trek", "Landevei");
INSERT INTO bikes (price, make, type) VALUES (4425, "Scott", "Terreng");
INSERT INTO bikes (price, make, type) VALUES (3008, "Scott", "Hybrid");
INSERT INTO bikes (price, make, type) VALUES (3601, "Scott", "Bysykkel");
INSERT INTO bikes (price, make, type) VALUES (4686, "Trek", "Landevei");
INSERT INTO bikes (price, make, type) VALUES (1747, "DBS", "Hybrid");
INSERT INTO bikes (price, make, type) VALUES (2605, "Merida", "Terreng");
INSERT INTO bikes (price, make, type) VALUES (2247, "Trek", "Bysykkel");
INSERT INTO bikes (price, make, type) VALUES (2376, "Trek", "Bysykkel");
INSERT INTO bikes (price, make, type) VALUES (1604, "Trek", "Landevei");
INSERT INTO bikes (price, make, type) VALUES (3844, "Trek", "Terreng");
INSERT INTO bikes (price, make, type) VALUES (2404, "Merida", "Bysykkel");
INSERT INTO bikes (price, make, type) VALUES (544, "Merida", "Terreng");
INSERT INTO bikes (price, make, type) VALUES (2349, "Merida", "Terreng");
INSERT INTO bikes (price, make, type) VALUES (4099, "Merida", "Terreng");
INSERT INTO bikes (price, make, type) VALUES (4499, "Merida", "Terreng");
INSERT INTO bikes (price, make, type) VALUES (4590, "Trek", "Terreng");
INSERT INTO bikes (price, make, type) VALUES (4336, "Scott", "Terreng");
INSERT INTO bikes (price, make, type) VALUES (4058, "Trek", "Bysykkel");
INSERT INTO bikes (price, make, type) VALUES (2006, "Merida", "Landevei");
INSERT INTO bikes (price, make, type) VALUES (817, "Merida", "Landevei");
INSERT INTO bikes (price, make, type) VALUES (4092, "Scott", "Terreng");
INSERT INTO bikes (price, make, type) VALUES (2203, "Merida", "Bysykkel");
INSERT INTO bikes (price, make, type) VALUES (2751, "Scott", "Hybrid");
INSERT INTO bikes (price, make, type) VALUES (3230, "DBS", "Landevei");
INSERT INTO bikes (price, make, type) VALUES (1119, "Merida", "Bysykkel");
INSERT INTO bikes (price, make, type) VALUES (4324, "Scott", "Landevei");
INSERT INTO bikes (price, make, type) VALUES (3447, "DBS", "Landevei");
INSERT INTO bikes (price, make, type) VALUES (3246, "DBS", "Landevei");
INSERT INTO bikes (price, make, type) VALUES (2030, "Scott", "Landevei");
INSERT INTO bikes (price, make, type) VALUES (1488, "Trek", "Hybrid");
INSERT INTO bikes (price, make, type) VALUES (3817, "Scott", "Landevei");
INSERT INTO bikes (price, make, type) VALUES (2561, "Scott", "Bysykkel");
INSERT INTO bikes (price, make, type) VALUES (987, "Merida", "Bysykkel");
INSERT INTO bikes (price, make, type) VALUES (710, "DBS", "Terreng");
INSERT INTO bikes (price, make, type) VALUES (1275, "Merida", "Terreng");
INSERT INTO bikes (price, make, type) VALUES (1185, "Scott", "Hybrid");
INSERT INTO bikes (price, make, type) VALUES (709, "Merida", "Bysykkel");
INSERT INTO bikes (price, make, type) VALUES (4327, "Scott", "Bysykkel");
INSERT INTO bikes (price, make, type) VALUES (3547, "Trek", "Hybrid");
INSERT INTO bikes (price, make, type) VALUES (856, "Trek", "Terreng");
INSERT INTO bikes (price, make, type) VALUES (2277, "Merida", "Terreng");
INSERT INTO bikes (price, make, type) VALUES (2895, "Scott", "Terreng");
INSERT INTO bikes (price, make, type) VALUES (4962, "Scott", "Bysykkel");
INSERT INTO bikes (price, make, type) VALUES (3694, "Merida", "Landevei");
INSERT INTO bikes (price, make, type) VALUES (3126, "Scott", "Bysykkel");
INSERT INTO bikes (price, make, type) VALUES (3516, "DBS", "Landevei");
INSERT INTO bikes (price, make, type) VALUES (1018, "Trek", "Terreng");
INSERT INTO bikes (price, make, type) VALUES (995, "Merida", "Bysykkel");
INSERT INTO bikes (price, make, type) VALUES (923, "DBS", "Landevei");
INSERT INTO bikes (price, make, type) VALUES (4578, "DBS", "Hybrid");
INSERT INTO bikes (price, make, type) VALUES (1937, "Trek", "Terreng");
INSERT INTO bikes (price, make, type) VALUES (4832, "Trek", "Bysykkel");
INSERT INTO bikes (price, make, type) VALUES (3381, "DBS", "Hybrid");
INSERT INTO bikes (price, make, type) VALUES (959, "Merida", "Terreng");
INSERT INTO bikes (price, make, type) VALUES (4567, "DBS", "Hybrid");
INSERT INTO bikes (price, make, type) VALUES (1620, "Trek", "Landevei");
INSERT INTO bikes (price, make, type) VALUES (3223, "Merida", "Terreng");
INSERT INTO bikes (price, make, type) VALUES (1968, "Trek", "Landevei");
INSERT INTO bikes (price, make, type) VALUES (799, "Merida", "Terreng");
INSERT INTO bikes (price, make, type) VALUES (3199, "DBS", "Landevei");
INSERT INTO bikes (price, make, type) VALUES (3538, "DBS", "Bysykkel");
INSERT INTO bikes (price, make, type) VALUES (1970, "Merida", "Bysykkel");
INSERT INTO bikes (price, make, type) VALUES (2107, "Merida", "Landevei");
INSERT INTO bikes (price, make, type) VALUES (4527, "DBS", "Hybrid");
INSERT INTO bikes (price, make, type) VALUES (3798, "DBS", "Landevei");
INSERT INTO bikes (price, make, type) VALUES (4847, "DBS", "Terreng");
INSERT INTO bikes (price, make, type) VALUES (514, "Trek", "Landevei");
INSERT INTO bikes (price, make, type) VALUES (2791, "DBS", "Terreng");
INSERT INTO bikes (price, make, type) VALUES (3188, "DBS", "Landevei");
INSERT INTO bikes (price, make, type) VALUES (1252, "Merida", "Landevei");
INSERT INTO bikes (price, make, type) VALUES (3498, "DBS", "Hybrid");
INSERT INTO bikes (price, make, type) VALUES (2458, "Merida", "Bysykkel");
INSERT INTO bikes (price, make, type) VALUES (2751, "Trek", "Landevei");
INSERT INTO bikes (price, make, type) VALUES (831, "DBS", "Hybrid");
INSERT INTO bikes (price, make, type) VALUES (1736, "DBS", "Terreng");
INSERT INTO bikes (price, make, type) VALUES (516, "Trek", "Landevei");
INSERT INTO bikes (price, make, type) VALUES (3945, "Merida", "Hybrid");
INSERT INTO bikes (price, make, type) VALUES (3462, "Trek", "Hybrid");
INSERT INTO bikes (price, make, type) VALUES (4176, "Scott", "Hybrid");
INSERT INTO bikes (price, make, type) VALUES (4192, "DBS", "Bysykkel");
INSERT INTO bikes (price, make, type) VALUES (1630, "DBS", "Bysykkel");
INSERT INTO bikes (price, make, type) VALUES (3448, "Merida", "Landevei");
INSERT INTO bikes (price, make, type) VALUES (2271, "DBS", "Hybrid");
INSERT INTO bikes (price, make, type) VALUES (3631, "Merida", "Terreng");
INSERT INTO bikes (price, make, type) VALUES (1839, "Merida", "Bysykkel");
INSERT INTO bikes (price, make, type) VALUES (4080, "Trek", "Bysykkel");
INSERT INTO bikes (price, make, type) VALUES (3384, "Merida", "Hybrid");
INSERT INTO bikes (price, make, type) VALUES (837, "DBS", "Bysykkel");
INSERT INTO bikes (price, make, type) VALUES (4402, "Trek", "Bysykkel");
INSERT INTO bikes (price, make, type) VALUES (501, "Scott", "Landevei");
INSERT INTO bikes (price, make, type) VALUES (2775, "Scott", "Hybrid");
INSERT INTO bikes (price, make, type) VALUES (4603, "Scott", "Landevei");
INSERT INTO bikes (price, make, type) VALUES (3355, "Trek", "Hybrid");
INSERT INTO bikes (price, make, type) VALUES (515, "Merida", "Terreng");
INSERT INTO bikes (price, make, type) VALUES (2168, "Merida", "Bysykkel");
INSERT INTO bikes (price, make, type) VALUES (2107, "Merida", "Landevei");
INSERT INTO bikes (price, make, type) VALUES (820, "DBS", "Landevei");
INSERT INTO bikes (price, make, type) VALUES (4737, "Scott", "Landevei");
INSERT INTO bikes (price, make, type) VALUES (4670, "Trek", "Landevei");
INSERT INTO bikes (price, make, type) VALUES (4887, "Trek", "Hybrid");
INSERT INTO bikes (price, make, type) VALUES (4146, "Trek", "Landevei");
INSERT INTO bikes (price, make, type) VALUES (4516, "Trek", "Bysykkel");
INSERT INTO bikes (price, make, type) VALUES (1213, "DBS", "Bysykkel");
INSERT INTO bikes (price, make, type) VALUES (3593, "Trek", "Hybrid");
INSERT INTO bikes (price, make, type) VALUES (1530, "Scott", "Hybrid");
INSERT INTO bikes (price, make, type) VALUES (4731, "Scott", "Bysykkel");
INSERT INTO bikes (price, make, type) VALUES (3176, "Trek", "Bysykkel");
INSERT INTO bikes (price, make, type) VALUES (1253, "Trek", "Bysykkel");
INSERT INTO bikes (price, make, type) VALUES (4870, "Scott", "Hybrid");
INSERT INTO bikes (price, make, type) VALUES (3386, "Merida", "Bysykkel");
INSERT INTO bikes (price, make, type) VALUES (1876, "DBS", "Hybrid");
INSERT INTO bikes (price, make, type) VALUES (1655, "DBS", "Terreng");
INSERT INTO bikes (price, make, type) VALUES (709, "Scott", "Hybrid");
INSERT INTO bikes (price, make, type) VALUES (4824, "Scott", "Bysykkel");
INSERT INTO bikes (price, make, type) VALUES (1733, "Merida", "Terreng");
INSERT INTO bikes (price, make, type) VALUES (4087, "Scott", "Landevei");
INSERT INTO bikes (price, make, type) VALUES (4840, "DBS", "Landevei");
INSERT INTO bikes (price, make, type) VALUES (1739, "DBS", "Landevei");
INSERT INTO bikes (price, make, type) VALUES (2086, "Merida", "Bysykkel");
INSERT INTO bikes (price, make, type) VALUES (3846, "DBS", "Landevei");
INSERT INTO bikes (price, make, type) VALUES (4524, "Trek", "Hybrid");
INSERT INTO bikes (price, make, type) VALUES (2942, "Trek", "Hybrid");
INSERT INTO bikes (price, make, type) VALUES (4385, "DBS", "Landevei");
INSERT INTO bikes (price, make, type) VALUES (4486, "Trek", "Hybrid");
INSERT INTO bikes (price, make, type) VALUES (4660, "Trek", "Bysykkel");
INSERT INTO bikes (price, make, type) VALUES (2049, "Scott", "Landevei");
INSERT INTO bikes (price, make, type) VALUES (3402, "Merida", "Terreng");
INSERT INTO bikes (price, make, type) VALUES (3467, "Scott", "Terreng");
INSERT INTO bikes (price, make, type) VALUES (599, "DBS", "Hybrid");
INSERT INTO bikes (price, make, type) VALUES (2434, "Trek", "Landevei");
INSERT INTO bikes (price, make, type) VALUES (4705, "DBS", "Landevei");
INSERT INTO bikes (price, make, type) VALUES (2254, "Scott", "Bysykkel");
INSERT INTO bikes (price, make, type) VALUES (3795, "DBS", "Terreng");
INSERT INTO bikes (price, make, type) VALUES (1064, "Scott", "Hybrid");
INSERT INTO bikes (price, make, type) VALUES (554, "Merida", "Terreng");
INSERT INTO bikes (price, make, type) VALUES (1615, "Trek", "Hybrid");
INSERT INTO bikes (price, make, type) VALUES (4390, "DBS", "Terreng");
INSERT INTO bikes (price, make, type) VALUES (4929, "Merida", "Bysykkel");
INSERT INTO bikes (price, make, type) VALUES (3595, "Merida", "Bysykkel");
INSERT INTO bikes (price, make, type) VALUES (1422, "DBS", "Landevei");
INSERT INTO bikes (price, make, type) VALUES (951, "Scott", "Hybrid");
INSERT INTO bikes (price, make, type) VALUES (1273, "Merida", "Bysykkel");
INSERT INTO bikes (price, make, type) VALUES (582, "Trek", "Terreng");
INSERT INTO bikes (price, make, type) VALUES (2222, "Merida", "Landevei");
INSERT INTO bikes (price, make, type) VALUES (3164, "Merida", "Terreng");
INSERT INTO bikes (price, make, type) VALUES (1769, "Scott", "Bysykkel");
INSERT INTO bikes (price, make, type) VALUES (3239, "DBS", "Landevei");
INSERT INTO bikes (price, make, type) VALUES (3019, "Merida", "Bysykkel");
INSERT INTO bikes (price, make, type) VALUES (777, "Trek", "Landevei");
INSERT INTO bikes (price, make, type) VALUES (2230, "Trek", "Terreng");
INSERT INTO bikes (price, make, type) VALUES (2026, "Trek", "Landevei");
INSERT INTO bikes (price, make, type) VALUES (3479, "Trek", "Hybrid");
INSERT INTO bikes (price, make, type) VALUES (2461, "Merida", "Terreng");
INSERT INTO bikes (price, make, type) VALUES (1940, "Trek", "Bysykkel");
INSERT INTO bikes (price, make, type) VALUES (4965, "Merida", "Hybrid");
INSERT INTO bikes (price, make, type) VALUES (3865, "Scott", "Terreng");
INSERT INTO bikes (price, make, type) VALUES (3434, "DBS", "Landevei");
INSERT INTO bikes (price, make, type) VALUES (2180, "Merida", "Landevei");
INSERT INTO bikes (price, make, type) VALUES (1644, "Merida", "Bysykkel");
INSERT INTO bikes (price, make, type) VALUES (729, "Merida", "Landevei");
INSERT INTO bikes (price, make, type) VALUES (2249, "Merida", "Bysykkel");
INSERT INTO bikes (price, make, type) VALUES (678, "Scott", "Bysykkel");
INSERT INTO bikes (price, make, type) VALUES (3833, "Trek", "Terreng");
INSERT INTO bikes (price, make, type) VALUES (4463, "Scott", "Hybrid");
INSERT INTO bikes (price, make, type) VALUES (1652, "Trek", "Bysykkel");
INSERT INTO bikes (price, make, type) VALUES (3950, "Scott", "Bysykkel");
INSERT INTO bikes (price, make, type) VALUES (1503, "Merida", "Landevei");
INSERT INTO bikes (price, make, type) VALUES (2262, "Trek", "Landevei");
INSERT INTO bikes (price, make, type) VALUES (3079, "Trek", "Bysykkel");
INSERT INTO bikes (price, make, type) VALUES (4998, "Trek", "Terreng");
INSERT INTO bikes (price, make, type) VALUES (1684, "Trek", "Landevei");
INSERT INTO bikes (price, make, type) VALUES (3929, "Trek", "Hybrid");
INSERT INTO bikes (price, make, type) VALUES (4209, "Scott", "Terreng");
INSERT INTO bikes (price, make, type) VALUES (2806, "Scott", "Terreng");
INSERT INTO bikes (price, make, type) VALUES (2235, "Trek", "Landevei");
INSERT INTO bikes (price, make, type) VALUES (3227, "Trek", "Terreng");
INSERT INTO bikes (price, make, type) VALUES (4531, "Scott", "Hybrid");
INSERT INTO bikes (price, make, type) VALUES (792, "Trek", "Landevei");
INSERT INTO bikes (price, make, type) VALUES (4357, "Trek", "Bysykkel");
INSERT INTO bikes (price, make, type) VALUES (3208, "Scott", "Landevei");
INSERT INTO bikes (price, make, type) VALUES (700, "Merida", "Terreng");
INSERT INTO bikes (price, make, type) VALUES (4683, "Merida", "Terreng");
INSERT INTO bikes (price, make, type) VALUES (1527, "DBS", "Landevei");
INSERT INTO bikes (price, make, type) VALUES (3356, "Merida", "Terreng");
INSERT INTO bikes (price, make, type) VALUES (2657, "Merida", "Bysykkel");
INSERT INTO bikes (price, make, type) VALUES (2471, "Scott", "Landevei");
INSERT INTO bikes (price, make, type) VALUES (641, "Trek", "Bysykkel");
INSERT INTO bikes (price, make, type) VALUES (4587, "Trek", "Terreng");
INSERT INTO bikes (price, make, type) VALUES (3141, "Trek", "Landevei");
INSERT INTO bikes (price, make, type) VALUES (638, "Merida", "Hybrid");
INSERT INTO bikes (price, make, type) VALUES (1870, "Scott", "Terreng");
INSERT INTO bikes (price, make, type) VALUES (1995, "Trek", "Landevei");
INSERT INTO bikes (price, make, type) VALUES (1304, "Merida", "Bysykkel");
INSERT INTO bikes (price, make, type) VALUES (2735, "Merida", "Terreng");
INSERT INTO bikes (price, make, type) VALUES (4095, "Scott", "Landevei");
INSERT INTO bikes (price, make, type) VALUES (3662, "Trek", "Bysykkel");
INSERT INTO bikes (price, make, type) VALUES (1660, "Trek", "Terreng");
INSERT INTO bikes (price, make, type) VALUES (2908, "DBS", "Bysykkel");
INSERT INTO bikes (price, make, type) VALUES (2223, "Merida", "Hybrid");

INSERT INTO docking_stations (stationName, maxSlots) VALUES ("Moholt, Trondheim", 2);
INSERT INTO docking_stations (stationName, maxSlots) VALUES ("Lade, Trondheim", 20);
INSERT INTO docking_stations (stationName, maxSlots) VALUES ("Kalvskinnet, Trondheim", 13);
INSERT INTO docking_stations (stationName, maxSlots) VALUES ("Gløshaugen, Trondheim", 17);
INSERT INTO docking_stations (stationName, maxSlots) VALUES ("Øya, Trondheim", 7);
INSERT INTO docking_stations (stationName, maxSlots) VALUES ("Tyholt, Trondheim", 24);
INSERT INTO docking_stations (stationName, maxSlots) VALUES ("Persaunet, Trondheim", 5);
INSERT INTO docking_stations (stationName, maxSlots) VALUES ("Charlottenlund, Trondheim", 9);
INSERT INTO docking_stations (stationName, maxSlots) VALUES ("Bakklandet, Trondheim", 10);
INSERT INTO docking_stations (stationName, maxSlots) VALUES ("Ila, Trondheim", 22);

INSERT INTO slots (slotID, stationID) VALUES (1, 1);
INSERT INTO slots (slotID, stationID) VALUES (2, 1);
INSERT INTO slots (slotID, stationID) VALUES (1, 2);
INSERT INTO slots (slotID, stationID) VALUES (2, 2);
INSERT INTO slots (slotID, stationID) VALUES (3, 2);
INSERT INTO slots (slotID, stationID) VALUES (4, 2);
INSERT INTO slots (slotID, stationID) VALUES (5, 2);
INSERT INTO slots (slotID, stationID) VALUES (6, 2);
INSERT INTO slots (slotID, stationID) VALUES (7, 2);
INSERT INTO slots (slotID, stationID) VALUES (8, 2);
INSERT INTO slots (slotID, stationID) VALUES (9, 2);
INSERT INTO slots (slotID, stationID) VALUES (10, 2);
INSERT INTO slots (slotID, stationID) VALUES (11, 2);
INSERT INTO slots (slotID, stationID) VALUES (12, 2);
INSERT INTO slots (slotID, stationID) VALUES (13, 2);
INSERT INTO slots (slotID, stationID) VALUES (14, 2);
INSERT INTO slots (slotID, stationID) VALUES (15, 2);
INSERT INTO slots (slotID, stationID) VALUES (16, 2);
INSERT INTO slots (slotID, stationID) VALUES (17, 2);
INSERT INTO slots (slotID, stationID) VALUES (18, 2);
INSERT INTO slots (slotID, stationID) VALUES (19, 2);
INSERT INTO slots (slotID, stationID) VALUES (20, 2);
INSERT INTO slots (slotID, stationID) VALUES (1, 3);
INSERT INTO slots (slotID, stationID) VALUES (2, 3);
INSERT INTO slots (slotID, stationID) VALUES (3, 3);
INSERT INTO slots (slotID, stationID) VALUES (4, 3);
INSERT INTO slots (slotID, stationID) VALUES (5, 3);
INSERT INTO slots (slotID, stationID) VALUES (6, 3);
INSERT INTO slots (slotID, stationID) VALUES (7, 3);
INSERT INTO slots (slotID, stationID) VALUES (8, 3);
INSERT INTO slots (slotID, stationID) VALUES (9, 3);
INSERT INTO slots (slotID, stationID) VALUES (10, 3);
INSERT INTO slots (slotID, stationID) VALUES (11, 3);
INSERT INTO slots (slotID, stationID) VALUES (12, 3);
INSERT INTO slots (slotID, stationID) VALUES (13, 3);
INSERT INTO slots (slotID, stationID) VALUES (1, 4);
INSERT INTO slots (slotID, stationID) VALUES (2, 4);
INSERT INTO slots (slotID, stationID) VALUES (3, 4);
INSERT INTO slots (slotID, stationID) VALUES (4, 4);
INSERT INTO slots (slotID, stationID) VALUES (5, 4);
INSERT INTO slots (slotID, stationID) VALUES (6, 4);
INSERT INTO slots (slotID, stationID) VALUES (7, 4);
INSERT INTO slots (slotID, stationID) VALUES (8, 4);
INSERT INTO slots (slotID, stationID) VALUES (9, 4);
INSERT INTO slots (slotID, stationID) VALUES (10, 4);
INSERT INTO slots (slotID, stationID) VALUES (11, 4);
INSERT INTO slots (slotID, stationID) VALUES (12, 4);
INSERT INTO slots (slotID, stationID) VALUES (13, 4);
INSERT INTO slots (slotID, stationID) VALUES (14, 4);
INSERT INTO slots (slotID, stationID) VALUES (15, 4);
INSERT INTO slots (slotID, stationID) VALUES (16, 4);
INSERT INTO slots (slotID, stationID) VALUES (17, 4);
INSERT INTO slots (slotID, stationID) VALUES (1, 5);
INSERT INTO slots (slotID, stationID) VALUES (2, 5);
INSERT INTO slots (slotID, stationID) VALUES (3, 5);
INSERT INTO slots (slotID, stationID) VALUES (4, 5);
INSERT INTO slots (slotID, stationID) VALUES (5, 5);
INSERT INTO slots (slotID, stationID) VALUES (6, 5);
INSERT INTO slots (slotID, stationID) VALUES (7, 5);
INSERT INTO slots (slotID, stationID) VALUES (1, 6);
INSERT INTO slots (slotID, stationID) VALUES (2, 6);
INSERT INTO slots (slotID, stationID) VALUES (3, 6);
INSERT INTO slots (slotID, stationID) VALUES (4, 6);
INSERT INTO slots (slotID, stationID) VALUES (5, 6);
INSERT INTO slots (slotID, stationID) VALUES (6, 6);
INSERT INTO slots (slotID, stationID) VALUES (7, 6);
INSERT INTO slots (slotID, stationID) VALUES (8, 6);
INSERT INTO slots (slotID, stationID) VALUES (9, 6);
INSERT INTO slots (slotID, stationID) VALUES (10, 6);
INSERT INTO slots (slotID, stationID) VALUES (11, 6);
INSERT INTO slots (slotID, stationID) VALUES (12, 6);
INSERT INTO slots (slotID, stationID) VALUES (13, 6);
INSERT INTO slots (slotID, stationID) VALUES (14, 6);
INSERT INTO slots (slotID, stationID) VALUES (15, 6);
INSERT INTO slots (slotID, stationID) VALUES (16, 6);
INSERT INTO slots (slotID, stationID) VALUES (17, 6);
INSERT INTO slots (slotID, stationID) VALUES (18, 6);
INSERT INTO slots (slotID, stationID) VALUES (19, 6);
INSERT INTO slots (slotID, stationID) VALUES (20, 6);
INSERT INTO slots (slotID, stationID) VALUES (21, 6);
INSERT INTO slots (slotID, stationID) VALUES (22, 6);
INSERT INTO slots (slotID, stationID) VALUES (23, 6);
INSERT INTO slots (slotID, stationID) VALUES (24, 6);
INSERT INTO slots (slotID, stationID) VALUES (1, 7);
INSERT INTO slots (slotID, stationID) VALUES (2, 7);
INSERT INTO slots (slotID, stationID) VALUES (3, 7);
INSERT INTO slots (slotID, stationID) VALUES (4, 7);
INSERT INTO slots (slotID, stationID) VALUES (5, 7);
INSERT INTO slots (slotID, stationID) VALUES (1, 8);
INSERT INTO slots (slotID, stationID) VALUES (2, 8);
INSERT INTO slots (slotID, stationID) VALUES (3, 8);
INSERT INTO slots (slotID, stationID) VALUES (4, 8);
INSERT INTO slots (slotID, stationID) VALUES (5, 8);
INSERT INTO slots (slotID, stationID) VALUES (6, 8);
INSERT INTO slots (slotID, stationID) VALUES (7, 8);
INSERT INTO slots (slotID, stationID) VALUES (8, 8);
INSERT INTO slots (slotID, stationID) VALUES (9, 8);
INSERT INTO slots (slotID, stationID) VALUES (1, 9);
INSERT INTO slots (slotID, stationID) VALUES (2, 9);
INSERT INTO slots (slotID, stationID) VALUES (3, 9);
INSERT INTO slots (slotID, stationID) VALUES (4, 9);
INSERT INTO slots (slotID, stationID) VALUES (5, 9);
INSERT INTO slots (slotID, stationID) VALUES (6, 9);
INSERT INTO slots (slotID, stationID) VALUES (7, 9);
INSERT INTO slots (slotID, stationID) VALUES (8, 9);
INSERT INTO slots (slotID, stationID) VALUES (9, 9);
INSERT INTO slots (slotID, stationID) VALUES (10, 9);
INSERT INTO slots (slotID, stationID) VALUES (1, 10);
INSERT INTO slots (slotID, stationID) VALUES (2, 10);
INSERT INTO slots (slotID, stationID) VALUES (3, 10);
INSERT INTO slots (slotID, stationID) VALUES (4, 10);
INSERT INTO slots (slotID, stationID) VALUES (5, 10);
INSERT INTO slots (slotID, stationID) VALUES (6, 10);
INSERT INTO slots (slotID, stationID) VALUES (7, 10);
INSERT INTO slots (slotID, stationID) VALUES (8, 10);
INSERT INTO slots (slotID, stationID) VALUES (9, 10);
INSERT INTO slots (slotID, stationID) VALUES (10, 10);
INSERT INTO slots (slotID, stationID) VALUES (11, 10);
INSERT INTO slots (slotID, stationID) VALUES (12, 10);
INSERT INTO slots (slotID, stationID) VALUES (13, 10);
INSERT INTO slots (slotID, stationID) VALUES (14, 10);
INSERT INTO slots (slotID, stationID) VALUES (15, 10);
INSERT INTO slots (slotID, stationID) VALUES (16, 10);
INSERT INTO slots (slotID, stationID) VALUES (17, 10);
INSERT INTO slots (slotID, stationID) VALUES (18, 10);
INSERT INTO slots (slotID, stationID) VALUES (19, 10);
INSERT INTO slots (slotID, stationID) VALUES (20, 10);
INSERT INTO slots (slotID, stationID) VALUES (21, 10);
INSERT INTO slots (slotID, stationID) VALUES (22, 10);

INSERT INTO user_types (description) VALUES ("Administrator");
INSERT INTO user_types (description) VALUES ("Reperatør");
INSERT INTO user_types (description) VALUES ("Kunde");
